if(typeof Math.imul == "undefined" || (Math.imul(0xffffffff,5) == 0)) {
    Math.imul = function (a, b) {
        var ah  = (a >>> 16) & 0xffff;
        var al = a & 0xffff;
        var bh  = (b >>> 16) & 0xffff;
        var bl = b & 0xffff;
        // the shift by 0 fixes the sign on the high part
        // the final |0 converts the unsigned value into a signed value
        return ((al * bl) + (((ah * bl + al * bh) << 16) >>> 0)|0);
    }
}


var f;
function r(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}var ba="closure_uid_"+(1E9*Math.random()>>>0),ca=0;function fa(a){return Array.prototype.join.call(arguments,"")};function ga(a,b){for(var c in a)b.call(void 0,a[c],c,a)};function ha(a,b){null!=a&&this.append.apply(this,arguments)}f=ha.prototype;f.Fa="";f.set=function(a){this.Fa=""+a};f.append=function(a,b,c){this.Fa+=a;if(null!=b)for(var d=1;d<arguments.length;d++)this.Fa+=arguments[d];return this};f.clear=function(){this.Fa=""};f.toString=function(){return this.Fa};if("undefined"===typeof ja)var ja=function(){throw Error("No *print-fn* fn set for evaluation environment");};var la=null;if("undefined"===typeof ma)var ma=null;function oa(){return new qa(null,5,[sa,!0,ta,!0,ua,!1,va,!1,wa,null],null)}function v(a){return null!=a&&!1!==a}function ya(a){return a instanceof Array}function x(a,b){return a[r(null==b?null:b)]?!0:a._?!0:!1}
function z(a,b){var c=null==b?null:b.constructor,c=v(v(c)?c.Bb:c)?c.Ab:r(b);return Error(["No protocol method ",a," defined for type ",c,": ",b].join(""))}function za(a){var b=a.Ab;return v(b)?b:""+C(a)}var Aa="undefined"!==typeof Symbol&&"function"===r(Symbol)?Symbol.iterator:"@@iterator";function Ba(a){for(var b=a.length,c=Array(b),d=0;;)if(d<b)c[d]=a[d],d+=1;else break;return c}
var Ca={},Fa={},Ga=function Ga(b){if(b?b.W:b)return b.W(b);var c;c=Ga[r(null==b?null:b)];if(!c&&(c=Ga._,!c))throw z("ICounted.-count",b);return c.call(null,b)},Ha=function Ha(b,c){if(b?b.I:b)return b.I(b,c);var d;d=Ha[r(null==b?null:b)];if(!d&&(d=Ha._,!d))throw z("ICollection.-conj",b);return d.call(null,b,c)},Ia={},D=function D(){switch(arguments.length){case 2:return D.c(arguments[0],arguments[1]);case 3:return D.i(arguments[0],arguments[1],arguments[2]);default:throw Error([C("Invalid arity: "),
C(arguments.length)].join(""));}};D.c=function(a,b){if(a?a.J:a)return a.J(a,b);var c;c=D[r(null==a?null:a)];if(!c&&(c=D._,!c))throw z("IIndexed.-nth",a);return c.call(null,a,b)};D.i=function(a,b,c){if(a?a.aa:a)return a.aa(a,b,c);var d;d=D[r(null==a?null:a)];if(!d&&(d=D._,!d))throw z("IIndexed.-nth",a);return d.call(null,a,b,c)};D.V=3;
var Ka={},E=function E(b){if(b?b.U:b)return b.U(b);var c;c=E[r(null==b?null:b)];if(!c&&(c=E._,!c))throw z("ISeq.-first",b);return c.call(null,b)},F=function F(b){if(b?b.$:b)return b.$(b);var c;c=F[r(null==b?null:b)];if(!c&&(c=F._,!c))throw z("ISeq.-rest",b);return c.call(null,b)},La={},Ma={},G=function G(){switch(arguments.length){case 2:return G.c(arguments[0],arguments[1]);case 3:return G.i(arguments[0],arguments[1],arguments[2]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));
}};G.c=function(a,b){if(a?a.R:a)return a.R(a,b);var c;c=G[r(null==a?null:a)];if(!c&&(c=G._,!c))throw z("ILookup.-lookup",a);return c.call(null,a,b)};G.i=function(a,b,c){if(a?a.F:a)return a.F(a,b,c);var d;d=G[r(null==a?null:a)];if(!d&&(d=G._,!d))throw z("ILookup.-lookup",a);return d.call(null,a,b,c)};G.V=3;
var Na=function Na(b,c,d){if(b?b.Ma:b)return b.Ma(b,c,d);var e;e=Na[r(null==b?null:b)];if(!e&&(e=Na._,!e))throw z("IAssociative.-assoc",b);return e.call(null,b,c,d)},Oa={},Pa={},Qa=function Qa(b){if(b?b.cb:b)return b.cb();var c;c=Qa[r(null==b?null:b)];if(!c&&(c=Qa._,!c))throw z("IMapEntry.-key",b);return c.call(null,b)},Ra=function Ra(b){if(b?b.eb:b)return b.eb();var c;c=Ra[r(null==b?null:b)];if(!c&&(c=Ra._,!c))throw z("IMapEntry.-val",b);return c.call(null,b)},Ta={},Ua=function Ua(b,c,d){if(b?b.fb:
b)return b.fb(b,c,d);var e;e=Ua[r(null==b?null:b)];if(!e&&(e=Ua._,!e))throw z("IVector.-assoc-n",b);return e.call(null,b,c,d)},Va={},Wa=function Wa(b){if(b?b.H:b)return b.H(b);var c;c=Wa[r(null==b?null:b)];if(!c&&(c=Wa._,!c))throw z("IMeta.-meta",b);return c.call(null,b)},Xa={},Ya=function Ya(b,c){if(b?b.M:b)return b.M(b,c);var d;d=Ya[r(null==b?null:b)];if(!d&&(d=Ya._,!d))throw z("IWithMeta.-with-meta",b);return d.call(null,b,c)},Za={},$a=function $a(){switch(arguments.length){case 2:return $a.c(arguments[0],
arguments[1]);case 3:return $a.i(arguments[0],arguments[1],arguments[2]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));}};$a.c=function(a,b){if(a?a.S:a)return a.S(a,b);var c;c=$a[r(null==a?null:a)];if(!c&&(c=$a._,!c))throw z("IReduce.-reduce",a);return c.call(null,a,b)};$a.i=function(a,b,c){if(a?a.T:a)return a.T(a,b,c);var d;d=$a[r(null==a?null:a)];if(!d&&(d=$a._,!d))throw z("IReduce.-reduce",a);return d.call(null,a,b,c)};$a.V=3;
var ab=function ab(b,c){if(b?b.o:b)return b.o(b,c);var d;d=ab[r(null==b?null:b)];if(!d&&(d=ab._,!d))throw z("IEquiv.-equiv",b);return d.call(null,b,c)},cb=function cb(b){if(b?b.C:b)return b.C(b);var c;c=cb[r(null==b?null:b)];if(!c&&(c=cb._,!c))throw z("IHash.-hash",b);return c.call(null,b)},db={},eb=function eb(b){if(b?b.L:b)return b.L(b);var c;c=eb[r(null==b?null:b)];if(!c&&(c=eb._,!c))throw z("ISeqable.-seq",b);return c.call(null,b)},fb={},I=function I(b,c){if(b?b.jb:b)return b.jb(0,c);var d;d=
I[r(null==b?null:b)];if(!d&&(d=I._,!d))throw z("IWriter.-write",b);return d.call(null,b,c)},gb={},hb=function hb(b,c,d){if(b?b.B:b)return b.B(b,c,d);var e;e=hb[r(null==b?null:b)];if(!e&&(e=hb._,!e))throw z("IPrintWithWriter.-pr-writer",b);return e.call(null,b,c,d)},ib=function ib(b,c,d){if(b?b.ib:b)return b.ib(0,c,d);var e;e=ib[r(null==b?null:b)];if(!e&&(e=ib._,!e))throw z("IWatchable.-notify-watches",b);return e.call(null,b,c,d)},jb=function jb(b){if(b?b.Ra:b)return b.Ra(b);var c;c=jb[r(null==b?
null:b)];if(!c&&(c=jb._,!c))throw z("IEditableCollection.-as-transient",b);return c.call(null,b)},kb=function kb(b,c){if(b?b.Va:b)return b.Va(b,c);var d;d=kb[r(null==b?null:b)];if(!d&&(d=kb._,!d))throw z("ITransientCollection.-conj!",b);return d.call(null,b,c)},lb=function lb(b){if(b?b.Wa:b)return b.Wa(b);var c;c=lb[r(null==b?null:b)];if(!c&&(c=lb._,!c))throw z("ITransientCollection.-persistent!",b);return c.call(null,b)},mb=function mb(b,c,d){if(b?b.Oa:b)return b.Oa(b,c,d);var e;e=mb[r(null==b?null:
b)];if(!e&&(e=mb._,!e))throw z("ITransientAssociative.-assoc!",b);return e.call(null,b,c,d)},ob=function ob(b,c,d){if(b?b.hb:b)return b.hb(0,c,d);var e;e=ob[r(null==b?null:b)];if(!e&&(e=ob._,!e))throw z("ITransientVector.-assoc-n!",b);return e.call(null,b,c,d)},pb=function pb(b){if(b?b.gb:b)return b.gb();var c;c=pb[r(null==b?null:b)];if(!c&&(c=pb._,!c))throw z("IChunk.-drop-first",b);return c.call(null,b)},qb=function qb(b){if(b?b.ab:b)return b.ab(b);var c;c=qb[r(null==b?null:b)];if(!c&&(c=qb._,!c))throw z("IChunkedSeq.-chunked-first",
b);return c.call(null,b)},rb=function rb(b){if(b?b.bb:b)return b.bb(b);var c;c=rb[r(null==b?null:b)];if(!c&&(c=rb._,!c))throw z("IChunkedSeq.-chunked-rest",b);return c.call(null,b)},sb=function sb(b){if(b?b.$a:b)return b.$a(b);var c;c=sb[r(null==b?null:b)];if(!c&&(c=sb._,!c))throw z("IChunkedNext.-chunked-next",b);return c.call(null,b)},tb=function tb(b,c){if(b?b.vb:b)return b.vb(b,c);var d;d=tb[r(null==b?null:b)];if(!d&&(d=tb._,!d))throw z("IReset.-reset!",b);return d.call(null,b,c)},J=function J(){switch(arguments.length){case 2:return J.c(arguments[0],
arguments[1]);case 3:return J.i(arguments[0],arguments[1],arguments[2]);case 4:return J.A(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return J.P(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));}};J.c=function(a,b){if(a?a.wb:a)return a.wb(a,b);var c;c=J[r(null==a?null:a)];if(!c&&(c=J._,!c))throw z("ISwap.-swap!",a);return c.call(null,a,b)};
J.i=function(a,b,c){if(a?a.xb:a)return a.xb(a,b,c);var d;d=J[r(null==a?null:a)];if(!d&&(d=J._,!d))throw z("ISwap.-swap!",a);return d.call(null,a,b,c)};J.A=function(a,b,c,d){if(a?a.yb:a)return a.yb(a,b,c,d);var e;e=J[r(null==a?null:a)];if(!e&&(e=J._,!e))throw z("ISwap.-swap!",a);return e.call(null,a,b,c,d)};J.P=function(a,b,c,d,e){if(a?a.zb:a)return a.zb(a,b,c,d,e);var g;g=J[r(null==a?null:a)];if(!g&&(g=J._,!g))throw z("ISwap.-swap!",a);return g.call(null,a,b,c,d,e)};J.V=5;
var ub=function ub(b){if(b?b.Na:b)return b.Na(b);var c;c=ub[r(null==b?null:b)];if(!c&&(c=ub._,!c))throw z("IIterable.-iterator",b);return c.call(null,b)};function vb(a){this.Cb=a;this.h=1073741824;this.u=0}vb.prototype.jb=function(a,b){return this.Cb.append(b)};function wb(a){var b=new ha;a.B(null,new vb(b),oa());return""+C(b)}
var xb="undefined"!==typeof Math.imul&&0!==Math.imul(4294967295,5)?function(a,b){return Math.imul(a,b)}:function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0};function zb(a){a=xb(a|0,-862048943);return xb(a<<15|a>>>-15,461845907)}function Ab(a,b){var c=(a|0)^(b|0);return xb(c<<13|c>>>-13,5)+-430675100|0}function Bb(a,b){var c=(a|0)^b,c=xb(c^c>>>16,-2048144789),c=xb(c^c>>>13,-1028477387);return c^c>>>16}
function Cb(a){var b;a:{b=1;for(var c=0;;)if(b<a.length){var d=b+2,c=Ab(c,zb(a.charCodeAt(b-1)|a.charCodeAt(b)<<16));b=d}else{b=c;break a}}b=1===(a.length&1)?b^zb(a.charCodeAt(a.length-1)):b;return Bb(b,xb(2,a.length))}var Db={},Eb=0;function Fb(a){255<Eb&&(Db={},Eb=0);var b=Db[a];if("number"!==typeof b){a:if(null!=a)if(b=a.length,0<b)for(var c=0,d=0;;)if(c<b)var e=c+1,d=xb(31,d)+a.charCodeAt(c),c=e;else{b=d;break a}else b=0;else b=0;Db[a]=b;Eb+=1}return a=b}
function Gb(a){a&&(a.h&4194304||a.Gb)?a=a.C(null):"number"===typeof a?a=Math.floor(a)%2147483647:!0===a?a=1:!1===a?a=0:"string"===typeof a?(a=Fb(a),0!==a&&(a=zb(a),a=Ab(0,a),a=Bb(a,4))):a=a instanceof Date?a.valueOf():null==a?0:cb(a);return a}function Hb(a,b){return a^b+2654435769+(a<<6)+(a>>2)}function Ib(a,b,c,d,e){this.Qa=a;this.name=b;this.Ea=c;this.Ia=d;this.ba=e;this.h=2154168321;this.u=4096}f=Ib.prototype;f.toString=function(){return this.Ea};f.equiv=function(a){return this.o(null,a)};
f.o=function(a,b){return b instanceof Ib?this.Ea===b.Ea:!1};f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return G.i(c,this,null);case 3:return G.i(c,this,d)}throw Error("Invalid arity: "+arguments.length);};a.c=function(a,c){return G.i(c,this,null)};a.i=function(a,c,d){return G.i(c,this,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ba(b)))};f.f=function(a){return G.i(a,this,null)};f.c=function(a,b){return G.i(a,this,b)};f.H=function(){return this.ba};
f.M=function(a,b){return new Ib(this.Qa,this.name,this.Ea,this.Ia,b)};f.C=function(){var a=this.Ia;return null!=a?a:this.Ia=a=Hb(Cb(this.name),Fb(this.Qa))};f.B=function(a,b){return I(b,this.Ea)};function L(a){if(null==a)return null;if(a&&(a.h&8388608||a.Hb))return a.L(null);if(ya(a)||"string"===typeof a)return 0===a.length?null:new M(a,0);if(x(db,a))return eb(a);throw Error([C(a),C(" is not ISeqable")].join(""));}
function N(a){if(null==a)return null;if(a&&(a.h&64||a.Ua))return a.U(null);a=L(a);return null==a?null:E(a)}function Jb(a){return null!=a?a&&(a.h&64||a.Ua)?a.$(null):(a=L(a))?F(a):Kb:Kb}function O(a){return null==a?null:a&&(a.h&128||a.Ta)?a.Y(null):L(Jb(a))}var P=function P(){switch(arguments.length){case 1:return P.f(arguments[0]);case 2:return P.c(arguments[0],arguments[1]);default:return P.w(arguments[0],arguments[1],new M(Array.prototype.slice.call(arguments,2),0))}};P.f=function(){return!0};
P.c=function(a,b){return null==a?null==b:a===b||ab(a,b)};P.w=function(a,b,c){for(;;)if(P.c(a,b))if(O(c))a=b,b=N(c),c=O(c);else return P.c(b,N(c));else return!1};P.N=function(a){var b=N(a),c=O(a);a=N(c);c=O(c);return P.w(b,a,c)};P.V=2;function Lb(a){this.s=a}Lb.prototype.next=function(){if(null!=this.s){var a=N(this.s);this.s=O(this.s);return{value:a,done:!1}}return{value:null,done:!0}};function Q(a){return new Lb(L(a))}function Mb(a,b){var c=zb(a),c=Ab(0,c);return Bb(c,b)}
function Nb(a){var b=0,c=1;for(a=L(a);;)if(null!=a)b+=1,c=xb(31,c)+Gb(N(a))|0,a=O(a);else return Mb(c,b)}var Ob=Mb(1,0);function Pb(a){var b=0,c=0;for(a=L(a);;)if(null!=a)b+=1,c=c+Gb(N(a))|0,a=O(a);else return Mb(c,b)}var Qb=Mb(0,0);Fa["null"]=!0;Ga["null"]=function(){return 0};Date.prototype.o=function(a,b){return b instanceof Date&&this.valueOf()===b.valueOf()};ab.number=function(a,b){return a===b};Ca["function"]=!0;Va["function"]=!0;Wa["function"]=function(){return null};
cb._=function(a){return a[ba]||(a[ba]=++ca)};function Rb(a,b){var c=Ga(a);if(0===c)return b.D?b.D():b.call(null);for(var d=D.c(a,0),e=1;;)if(e<c)var g=D.c(a,e),d=b.c?b.c(d,g):b.call(null,d,g),e=e+1;else return d}function Sb(a,b,c){var d=Ga(a),e=c;for(c=0;;)if(c<d){var g=D.c(a,c),e=b.c?b.c(e,g):b.call(null,e,g);c+=1}else return e}function Tb(a,b){var c=a.length;if(0===a.length)return b.D?b.D():b.call(null);for(var d=a[0],e=1;;)if(e<c)var g=a[e],d=b.c?b.c(d,g):b.call(null,d,g),e=e+1;else return d}
function Ub(a,b,c){var d=a.length,e=c;for(c=0;;)if(c<d){var g=a[c],e=b.c?b.c(e,g):b.call(null,e,g);c+=1}else return e}function Vb(a,b,c,d){for(var e=a.length;;)if(d<e){var g=a[d];c=b.c?b.c(c,g):b.call(null,c,g);d+=1}else return c}function Wb(a){return a?a.h&2||a.mb?!0:a.h?!1:x(Fa,a):x(Fa,a)}function Yb(a,b){this.a=a;this.j=b}Yb.prototype.Xa=function(){return this.j<this.a.length};Yb.prototype.next=function(){var a=this.a[this.j];this.j+=1;return a};
function M(a,b){this.a=a;this.j=b;this.h=166199550;this.u=8192}f=M.prototype;f.toString=function(){return wb(this)};f.equiv=function(a){return this.o(null,a)};f.J=function(a,b){var c=b+this.j;return c<this.a.length?this.a[c]:null};f.aa=function(a,b,c){a=b+this.j;return a<this.a.length?this.a[a]:c};f.Na=function(){return new Yb(this.a,this.j)};f.Y=function(){return this.j+1<this.a.length?new M(this.a,this.j+1):null};f.W=function(){var a=this.a.length-this.j;return 0>a?0:a};f.C=function(){return Nb(this)};
f.o=function(a,b){return Zb.c?Zb.c(this,b):Zb.call(null,this,b)};f.S=function(a,b){return Vb(this.a,b,this.a[this.j],this.j+1)};f.T=function(a,b,c){return Vb(this.a,b,c,this.j)};f.U=function(){return this.a[this.j]};f.$=function(){return this.j+1<this.a.length?new M(this.a,this.j+1):Kb};f.L=function(){return this.j<this.a.length?this:null};f.I=function(a,b){return R.c?R.c(b,this):R.call(null,b,this)};M.prototype[Aa]=function(){return Q(this)};function $b(a,b){return b<a.length?new M(a,b):null}
function ac(){switch(arguments.length){case 1:return $b(arguments[0],0);case 2:return $b(arguments[0],arguments[1]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));}}ab._=function(a,b){return a===b};var bc=function bc(){switch(arguments.length){case 0:return bc.D();case 1:return bc.f(arguments[0]);case 2:return bc.c(arguments[0],arguments[1]);default:return bc.w(arguments[0],arguments[1],new M(Array.prototype.slice.call(arguments,2),0))}};bc.D=function(){return cc};bc.f=function(a){return a};
bc.c=function(a,b){return null!=a?Ha(a,b):Ha(Kb,b)};bc.w=function(a,b,c){for(;;)if(v(c))a=bc.c(a,b),b=N(c),c=O(c);else return bc.c(a,b)};bc.N=function(a){var b=N(a),c=O(a);a=N(c);c=O(c);return bc.w(b,a,c)};bc.V=2;function S(a){if(null!=a)if(a&&(a.h&2||a.mb))a=a.W(null);else if(ya(a))a=a.length;else if("string"===typeof a)a=a.length;else if(x(Fa,a))a=Ga(a);else a:{a=L(a);for(var b=0;;){if(Wb(a)){a=b+Ga(a);break a}a=O(a);b+=1}}else a=0;return a}
function dc(a,b){for(var c=null;;){if(null==a)return c;if(0===b)return L(a)?N(a):c;var d=a;if(d?d.h&16||d.ob||(d.h?0:x(Ia,d)):x(Ia,d))return D.i(a,b,c);if(L(a)){var d=O(a),e=b-1;a=d;b=e}else return c}}
function T(a,b){if("number"!==typeof b)throw Error("index argument to nth must be a number.");if(null==a)return null;if(a&&(a.h&16||a.ob))return a.aa(null,b,null);if(ya(a)||"string"===typeof a)return b<a.length?a[b]:null;if(x(Ia,a))return D.c(a,b);if(a?a.h&64||a.Ua||(a.h?0:x(Ka,a)):x(Ka,a))return dc(a,b);throw Error([C("nth not supported on this type "),C(za(null==a?null:a.constructor))].join(""));}
function ec(a,b){return null==a?null:a&&(a.h&256||a.pb)?a.R(null,b):ya(a)?b<a.length?a[b|0]:null:"string"===typeof a?b<a.length?a[b|0]:null:x(Ma,a)?G.c(a,b):null}function fc(a,b,c){return null!=a?a&&(a.h&256||a.pb)?a.F(null,b,c):ya(a)?b<a.length?a[b]:c:"string"===typeof a?b<a.length?a[b]:c:x(Ma,a)?G.i(a,b,c):c:c}
var gc=function gc(){switch(arguments.length){case 3:return gc.i(arguments[0],arguments[1],arguments[2]);default:return gc.w(arguments[0],arguments[1],arguments[2],new M(Array.prototype.slice.call(arguments,3),0))}};gc.i=function(a,b,c){if(null!=a)a=Na(a,b,c);else a:{a=[b];c=[c];b=a.length;var d=0,e;for(e=jb(hc);;)if(d<b){var g=d+1;e=e.Oa(null,a[d],c[d]);d=g}else{a=lb(e);break a}}return a};gc.w=function(a,b,c,d){for(;;)if(a=gc.i(a,b,c),v(d))b=N(d),c=N(O(d)),d=O(O(d));else return a};
gc.N=function(a){var b=N(a),c=O(a);a=N(c);var d=O(c),c=N(d),d=O(d);return gc.w(b,a,c,d)};gc.V=3;function ic(a){var b="function"==r(a);return v(b)?b:a?v(v(null)?null:a.lb)?!0:a.Mb?!1:x(Ca,a):x(Ca,a)}function jc(a,b){this.b=a;this.m=b;this.h=393217;this.u=0}f=jc.prototype;f.H=function(){return this.m};f.M=function(a,b){return new jc(this.b,b)};f.lb=!0;
f.call=function(){function a(a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,y,H,K,ea){a=this.b;return kc.Sa?kc.Sa(a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,y,H,K,ea):kc.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,y,H,K,ea)}function b(a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,y,H,K){a=this;return a.b.ua?a.b.ua(b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,y,H,K):a.b.call(null,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,y,H,K)}function c(a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,y,H){a=this;return a.b.ta?a.b.ta(b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,y,
H):a.b.call(null,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,y,H)}function d(a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,y){a=this;return a.b.sa?a.b.sa(b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,y):a.b.call(null,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,y)}function e(a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B){a=this;return a.b.ra?a.b.ra(b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B):a.b.call(null,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B)}function g(a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A){a=this;return a.b.qa?a.b.qa(b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A):a.b.call(null,
b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A)}function h(a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w){a=this;return a.b.pa?a.b.pa(b,c,d,e,g,h,k,l,m,n,p,q,t,u,w):a.b.call(null,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w)}function k(a,b,c,d,e,g,h,k,l,m,n,p,q,t,u){a=this;return a.b.oa?a.b.oa(b,c,d,e,g,h,k,l,m,n,p,q,t,u):a.b.call(null,b,c,d,e,g,h,k,l,m,n,p,q,t,u)}function l(a,b,c,d,e,g,h,k,l,m,n,p,q,t){a=this;return a.b.na?a.b.na(b,c,d,e,g,h,k,l,m,n,p,q,t):a.b.call(null,b,c,d,e,g,h,k,l,m,n,p,q,t)}function m(a,b,c,d,e,g,h,k,l,m,n,p,q){a=this;
return a.b.ma?a.b.ma(b,c,d,e,g,h,k,l,m,n,p,q):a.b.call(null,b,c,d,e,g,h,k,l,m,n,p,q)}function n(a,b,c,d,e,g,h,k,l,m,n,p){a=this;return a.b.la?a.b.la(b,c,d,e,g,h,k,l,m,n,p):a.b.call(null,b,c,d,e,g,h,k,l,m,n,p)}function p(a,b,c,d,e,g,h,k,l,m,n){a=this;return a.b.ka?a.b.ka(b,c,d,e,g,h,k,l,m,n):a.b.call(null,b,c,d,e,g,h,k,l,m,n)}function q(a,b,c,d,e,g,h,k,l,m){a=this;return a.b.ya?a.b.ya(b,c,d,e,g,h,k,l,m):a.b.call(null,b,c,d,e,g,h,k,l,m)}function t(a,b,c,d,e,g,h,k,l){a=this;return a.b.xa?a.b.xa(b,c,
d,e,g,h,k,l):a.b.call(null,b,c,d,e,g,h,k,l)}function u(a,b,c,d,e,g,h,k){a=this;return a.b.wa?a.b.wa(b,c,d,e,g,h,k):a.b.call(null,b,c,d,e,g,h,k)}function w(a,b,c,d,e,g,h){a=this;return a.b.va?a.b.va(b,c,d,e,g,h):a.b.call(null,b,c,d,e,g,h)}function A(a,b,c,d,e,g){a=this;return a.b.P?a.b.P(b,c,d,e,g):a.b.call(null,b,c,d,e,g)}function B(a,b,c,d,e){a=this;return a.b.A?a.b.A(b,c,d,e):a.b.call(null,b,c,d,e)}function H(a,b,c,d){a=this;return a.b.i?a.b.i(b,c,d):a.b.call(null,b,c,d)}function K(a,b,c){a=this;
return a.b.c?a.b.c(b,c):a.b.call(null,b,c)}function ea(a,b){a=this;return a.b.f?a.b.f(b):a.b.call(null,b)}function Ea(a){a=this;return a.b.D?a.b.D():a.b.call(null)}var y=null,y=function(y,W,Y,aa,da,ia,ka,na,pa,ra,xa,Da,Ja,Sa,bb,nb,yb,Xb,Ac,Zc,Qd,De){switch(arguments.length){case 1:return Ea.call(this,y);case 2:return ea.call(this,y,W);case 3:return K.call(this,y,W,Y);case 4:return H.call(this,y,W,Y,aa);case 5:return B.call(this,y,W,Y,aa,da);case 6:return A.call(this,y,W,Y,aa,da,ia);case 7:return w.call(this,
y,W,Y,aa,da,ia,ka);case 8:return u.call(this,y,W,Y,aa,da,ia,ka,na);case 9:return t.call(this,y,W,Y,aa,da,ia,ka,na,pa);case 10:return q.call(this,y,W,Y,aa,da,ia,ka,na,pa,ra);case 11:return p.call(this,y,W,Y,aa,da,ia,ka,na,pa,ra,xa);case 12:return n.call(this,y,W,Y,aa,da,ia,ka,na,pa,ra,xa,Da);case 13:return m.call(this,y,W,Y,aa,da,ia,ka,na,pa,ra,xa,Da,Ja);case 14:return l.call(this,y,W,Y,aa,da,ia,ka,na,pa,ra,xa,Da,Ja,Sa);case 15:return k.call(this,y,W,Y,aa,da,ia,ka,na,pa,ra,xa,Da,Ja,Sa,bb);case 16:return h.call(this,
y,W,Y,aa,da,ia,ka,na,pa,ra,xa,Da,Ja,Sa,bb,nb);case 17:return g.call(this,y,W,Y,aa,da,ia,ka,na,pa,ra,xa,Da,Ja,Sa,bb,nb,yb);case 18:return e.call(this,y,W,Y,aa,da,ia,ka,na,pa,ra,xa,Da,Ja,Sa,bb,nb,yb,Xb);case 19:return d.call(this,y,W,Y,aa,da,ia,ka,na,pa,ra,xa,Da,Ja,Sa,bb,nb,yb,Xb,Ac);case 20:return c.call(this,y,W,Y,aa,da,ia,ka,na,pa,ra,xa,Da,Ja,Sa,bb,nb,yb,Xb,Ac,Zc);case 21:return b.call(this,y,W,Y,aa,da,ia,ka,na,pa,ra,xa,Da,Ja,Sa,bb,nb,yb,Xb,Ac,Zc,Qd);case 22:return a.call(this,y,W,Y,aa,da,ia,ka,
na,pa,ra,xa,Da,Ja,Sa,bb,nb,yb,Xb,Ac,Zc,Qd,De)}throw Error("Invalid arity: "+arguments.length);};y.f=Ea;y.c=ea;y.i=K;y.A=H;y.P=B;y.va=A;y.wa=w;y.xa=u;y.ya=t;y.ka=q;y.la=p;y.ma=n;y.na=m;y.oa=l;y.pa=k;y.qa=h;y.ra=g;y.sa=e;y.ta=d;y.ua=c;y.nb=b;y.Sa=a;return y}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ba(b)))};f.D=function(){return this.b.D?this.b.D():this.b.call(null)};f.f=function(a){return this.b.f?this.b.f(a):this.b.call(null,a)};
f.c=function(a,b){return this.b.c?this.b.c(a,b):this.b.call(null,a,b)};f.i=function(a,b,c){return this.b.i?this.b.i(a,b,c):this.b.call(null,a,b,c)};f.A=function(a,b,c,d){return this.b.A?this.b.A(a,b,c,d):this.b.call(null,a,b,c,d)};f.P=function(a,b,c,d,e){return this.b.P?this.b.P(a,b,c,d,e):this.b.call(null,a,b,c,d,e)};f.va=function(a,b,c,d,e,g){return this.b.va?this.b.va(a,b,c,d,e,g):this.b.call(null,a,b,c,d,e,g)};
f.wa=function(a,b,c,d,e,g,h){return this.b.wa?this.b.wa(a,b,c,d,e,g,h):this.b.call(null,a,b,c,d,e,g,h)};f.xa=function(a,b,c,d,e,g,h,k){return this.b.xa?this.b.xa(a,b,c,d,e,g,h,k):this.b.call(null,a,b,c,d,e,g,h,k)};f.ya=function(a,b,c,d,e,g,h,k,l){return this.b.ya?this.b.ya(a,b,c,d,e,g,h,k,l):this.b.call(null,a,b,c,d,e,g,h,k,l)};f.ka=function(a,b,c,d,e,g,h,k,l,m){return this.b.ka?this.b.ka(a,b,c,d,e,g,h,k,l,m):this.b.call(null,a,b,c,d,e,g,h,k,l,m)};
f.la=function(a,b,c,d,e,g,h,k,l,m,n){return this.b.la?this.b.la(a,b,c,d,e,g,h,k,l,m,n):this.b.call(null,a,b,c,d,e,g,h,k,l,m,n)};f.ma=function(a,b,c,d,e,g,h,k,l,m,n,p){return this.b.ma?this.b.ma(a,b,c,d,e,g,h,k,l,m,n,p):this.b.call(null,a,b,c,d,e,g,h,k,l,m,n,p)};f.na=function(a,b,c,d,e,g,h,k,l,m,n,p,q){return this.b.na?this.b.na(a,b,c,d,e,g,h,k,l,m,n,p,q):this.b.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q)};
f.oa=function(a,b,c,d,e,g,h,k,l,m,n,p,q,t){return this.b.oa?this.b.oa(a,b,c,d,e,g,h,k,l,m,n,p,q,t):this.b.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,t)};f.pa=function(a,b,c,d,e,g,h,k,l,m,n,p,q,t,u){return this.b.pa?this.b.pa(a,b,c,d,e,g,h,k,l,m,n,p,q,t,u):this.b.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,t,u)};f.qa=function(a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w){return this.b.qa?this.b.qa(a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w):this.b.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w)};
f.ra=function(a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A){return this.b.ra?this.b.ra(a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A):this.b.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A)};f.sa=function(a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B){return this.b.sa?this.b.sa(a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B):this.b.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B)};
f.ta=function(a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,H){return this.b.ta?this.b.ta(a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,H):this.b.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,H)};f.ua=function(a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,H,K){return this.b.ua?this.b.ua(a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,H,K):this.b.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,H,K)};
f.nb=function(a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,H,K,ea){var Ea=this.b;return kc.Sa?kc.Sa(Ea,a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,H,K,ea):kc.call(null,Ea,a,b,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,H,K,ea)};function lc(a){var b=null!=a;return(b?a?a.h&131072||a.sb||(a.h?0:x(Va,a)):x(Va,a):b)?Wa(a):null}function mc(a){return null==a?!1:a?a.h&1024||a.qb?!0:a.h?!1:x(Oa,a):x(Oa,a)}function nc(a){return a?a.h&16384||a.Jb?!0:a.h?!1:x(Ta,a):x(Ta,a)}function oc(a){return a?a.u&512||a.Eb?!0:!1:!1}
function pc(a){var b=[];ga(a,function(a,b){return function(a,c){return b.push(c)}}(a,b));return b}function qc(a,b,c,d,e){for(;0!==e;)c[d]=a[b],d+=1,--e,b+=1}var rc={};function sc(a){return null==a?!1:a?a.h&64||a.Ua?!0:a.h?!1:x(Ka,a):x(Ka,a)}function tc(a){return v(a)?!0:!1}function uc(a,b){var c=L(b);if(c){var d=N(c),c=O(c);return vc?vc(a,d,c):wc.call(null,a,d,c)}return a.D?a.D():a.call(null)}function xc(a,b,c){for(c=L(c);;)if(c){var d=N(c);b=a.c?a.c(b,d):a.call(null,b,d);c=O(c)}else return b}
function wc(){switch(arguments.length){case 2:var a=arguments[0],b=arguments[1];return b&&(b.h&524288||b.ub)?b.S(null,a):ya(b)?Tb(b,a):"string"===typeof b?Tb(b,a):x(Za,b)?$a.c(b,a):uc(a,b);case 3:return vc(arguments[0],arguments[1],arguments[2]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));}}function vc(a,b,c){return c&&(c.h&524288||c.ub)?c.T(null,a,b):ya(c)?Ub(c,a,b):"string"===typeof c?Ub(c,a,b):x(Za,c)?$a.i(c,a,b):xc(a,b,c)}function yc(a){return a}
function zc(a){a=(a-a%2)/2;return 0<=a?Math.floor(a):Math.ceil(a)}function Bc(a){a-=a>>1&1431655765;a=(a&858993459)+(a>>2&858993459);return 16843009*(a+(a>>4)&252645135)>>24}var C=function C(){switch(arguments.length){case 0:return C.D();case 1:return C.f(arguments[0]);default:return C.w(arguments[0],new M(Array.prototype.slice.call(arguments,1),0))}};C.D=function(){return""};C.f=function(a){return null==a?"":fa(a)};
C.w=function(a,b){for(var c=new ha(""+C(a)),d=b;;)if(v(d))c=c.append(""+C(N(d))),d=O(d);else return c.toString()};C.N=function(a){var b=N(a);a=O(a);return C.w(b,a)};C.V=1;function Zb(a,b){var c;if(b?b.h&16777216||b.Ib||(b.h?0:x(fb,b)):x(fb,b))if(Wb(a)&&Wb(b)&&S(a)!==S(b))c=!1;else a:{c=L(a);for(var d=L(b);;){if(null==c){c=null==d;break a}if(null!=d&&P.c(N(c),N(d)))c=O(c),d=O(d);else{c=!1;break a}}}else c=null;return tc(c)}
function Cc(a,b,c,d,e){this.m=a;this.first=b;this.za=c;this.count=d;this.l=e;this.h=65937646;this.u=8192}f=Cc.prototype;f.toString=function(){return wb(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.m};f.Y=function(){return 1===this.count?null:this.za};f.W=function(){return this.count};f.C=function(){var a=this.l;return null!=a?a:this.l=a=Nb(this)};f.o=function(a,b){return Zb(this,b)};f.S=function(a,b){return uc(b,this)};f.T=function(a,b,c){return xc(b,c,this)};f.U=function(){return this.first};
f.$=function(){return 1===this.count?Kb:this.za};f.L=function(){return this};f.M=function(a,b){return new Cc(b,this.first,this.za,this.count,this.l)};f.I=function(a,b){return new Cc(this.m,b,this,this.count+1,null)};Cc.prototype[Aa]=function(){return Q(this)};function Dc(a){this.m=a;this.h=65937614;this.u=8192}f=Dc.prototype;f.toString=function(){return wb(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.m};f.Y=function(){return null};f.W=function(){return 0};f.C=function(){return Ob};
f.o=function(a,b){return Zb(this,b)};f.S=function(a,b){return uc(b,this)};f.T=function(a,b,c){return xc(b,c,this)};f.U=function(){return null};f.$=function(){return Kb};f.L=function(){return null};f.M=function(a,b){return new Dc(b)};f.I=function(a,b){return new Cc(this.m,b,null,1,null)};var Kb=new Dc(null);Dc.prototype[Aa]=function(){return Q(this)};
function Ec(){a:{var a=0<arguments.length?new M(Array.prototype.slice.call(arguments,0),0):null,b;if(a instanceof M&&0===a.j)b=a.a;else b:for(b=[];;)if(null!=a)b.push(a.U(null)),a=a.Y(null);else break b;for(var a=b.length,c=Kb;;)if(0<a)var d=a-1,c=c.I(null,b[a-1]),a=d;else break a}return c}function Fc(a,b,c,d){this.m=a;this.first=b;this.za=c;this.l=d;this.h=65929452;this.u=8192}f=Fc.prototype;f.toString=function(){return wb(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.m};
f.Y=function(){return null==this.za?null:L(this.za)};f.C=function(){var a=this.l;return null!=a?a:this.l=a=Nb(this)};f.o=function(a,b){return Zb(this,b)};f.S=function(a,b){return uc(b,this)};f.T=function(a,b,c){return xc(b,c,this)};f.U=function(){return this.first};f.$=function(){return null==this.za?Kb:this.za};f.L=function(){return this};f.M=function(a,b){return new Fc(b,this.first,this.za,this.l)};f.I=function(a,b){return new Fc(null,b,this,this.l)};Fc.prototype[Aa]=function(){return Q(this)};
function R(a,b){var c=null==b;return(c?c:b&&(b.h&64||b.Ua))?new Fc(null,a,b,null):new Fc(null,a,L(b),null)}function U(a,b,c,d){this.Qa=a;this.name=b;this.Ca=c;this.Ia=d;this.h=2153775105;this.u=4096}f=U.prototype;f.toString=function(){return[C(":"),C(this.Ca)].join("")};f.equiv=function(a){return this.o(null,a)};f.o=function(a,b){return b instanceof U?this.Ca===b.Ca:!1};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return ec(c,this);case 3:return fc(c,this,d)}throw Error("Invalid arity: "+arguments.length);};a.c=function(a,c){return ec(c,this)};a.i=function(a,c,d){return fc(c,this,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ba(b)))};f.f=function(a){return ec(a,this)};f.c=function(a,b){return fc(a,this,b)};
f.C=function(){var a=this.Ia;return null!=a?a:this.Ia=a=Hb(Cb(this.name),Fb(this.Qa))+2654435769|0};f.B=function(a,b){return I(b,[C(":"),C(this.Ca)].join(""))};var Gc=function Gc(){switch(arguments.length){case 1:return Gc.f(arguments[0]);case 2:return Gc.c(arguments[0],arguments[1]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));}};
Gc.f=function(a){if(a instanceof U)return a;if(a instanceof Ib){var b;if(a&&(a.u&4096||a.tb))b=a.Qa;else throw Error([C("Doesn't support namespace: "),C(a)].join(""));return new U(b,Hc.f?Hc.f(a):Hc.call(null,a),a.Ea,null)}return"string"===typeof a?(b=a.split("/"),2===b.length?new U(b[0],b[1],a,null):new U(null,b[0],a,null)):null};Gc.c=function(a,b){return new U(a,b,[C(v(a)?[C(a),C("/")].join(""):null),C(b)].join(""),null)};Gc.V=2;
function Ic(a,b,c,d){this.m=a;this.Ka=b;this.s=c;this.l=d;this.h=32374988;this.u=0}f=Ic.prototype;f.toString=function(){return wb(this)};f.equiv=function(a){return this.o(null,a)};function Jc(a){null!=a.Ka&&(a.s=a.Ka.D?a.Ka.D():a.Ka.call(null),a.Ka=null);return a.s}f.H=function(){return this.m};f.Y=function(){eb(this);return null==this.s?null:O(this.s)};f.C=function(){var a=this.l;return null!=a?a:this.l=a=Nb(this)};f.o=function(a,b){return Zb(this,b)};f.S=function(a,b){return uc(b,this)};
f.T=function(a,b,c){return xc(b,c,this)};f.U=function(){eb(this);return null==this.s?null:N(this.s)};f.$=function(){eb(this);return null!=this.s?Jb(this.s):Kb};f.L=function(){Jc(this);if(null==this.s)return null;for(var a=this.s;;)if(a instanceof Ic)a=Jc(a);else return this.s=a,L(this.s)};f.M=function(a,b){return new Ic(b,this.Ka,this.s,this.l)};f.I=function(a,b){return R(b,this)};Ic.prototype[Aa]=function(){return Q(this)};function Kc(a,b){this.Za=a;this.end=b;this.h=2;this.u=0}
Kc.prototype.add=function(a){this.Za[this.end]=a;return this.end+=1};Kc.prototype.ca=function(){var a=new Lc(this.Za,0,this.end);this.Za=null;return a};Kc.prototype.W=function(){return this.end};function Lc(a,b,c){this.a=a;this.O=b;this.end=c;this.h=524306;this.u=0}f=Lc.prototype;f.W=function(){return this.end-this.O};f.J=function(a,b){return this.a[this.O+b]};f.aa=function(a,b,c){return 0<=b&&b<this.end-this.O?this.a[this.O+b]:c};
f.gb=function(){if(this.O===this.end)throw Error("-drop-first of empty chunk");return new Lc(this.a,this.O+1,this.end)};f.S=function(a,b){return Vb(this.a,b,this.a[this.O],this.O+1)};f.T=function(a,b,c){return Vb(this.a,b,c,this.O)};function Mc(a,b,c,d){this.ca=a;this.ia=b;this.m=c;this.l=d;this.h=31850732;this.u=1536}f=Mc.prototype;f.toString=function(){return wb(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.m};
f.Y=function(){if(1<Ga(this.ca))return new Mc(pb(this.ca),this.ia,this.m,null);var a=eb(this.ia);return null==a?null:a};f.C=function(){var a=this.l;return null!=a?a:this.l=a=Nb(this)};f.o=function(a,b){return Zb(this,b)};f.U=function(){return D.c(this.ca,0)};f.$=function(){return 1<Ga(this.ca)?new Mc(pb(this.ca),this.ia,this.m,null):null==this.ia?Kb:this.ia};f.L=function(){return this};f.ab=function(){return this.ca};f.bb=function(){return null==this.ia?Kb:this.ia};
f.M=function(a,b){return new Mc(this.ca,this.ia,b,this.l)};f.I=function(a,b){return R(b,this)};f.$a=function(){return null==this.ia?null:this.ia};Mc.prototype[Aa]=function(){return Q(this)};function Nc(a,b){return 0===Ga(a)?b:new Mc(a,b,null,null)}function Oc(a,b){a.add(b)}function Pc(a){for(var b=[];;)if(L(a))b.push(N(a)),a=O(a);else return b}function Qc(a,b){if(Wb(a))return S(a);for(var c=a,d=b,e=0;;)if(0<d&&L(c))c=O(c),--d,e+=1;else return e}
var Rc=function Rc(b){return null==b?null:null==O(b)?L(N(b)):R(N(b),Rc(O(b)))};
function Sc(a,b,c){var d=L(c);if(0===b)return a.D?a.D():a.call(null);c=E(d);var e=F(d);if(1===b)return a.f?a.f(c):a.f?a.f(c):a.call(null,c);var d=E(e),g=F(e);if(2===b)return a.c?a.c(c,d):a.c?a.c(c,d):a.call(null,c,d);var e=E(g),h=F(g);if(3===b)return a.i?a.i(c,d,e):a.i?a.i(c,d,e):a.call(null,c,d,e);var g=E(h),k=F(h);if(4===b)return a.A?a.A(c,d,e,g):a.A?a.A(c,d,e,g):a.call(null,c,d,e,g);var h=E(k),l=F(k);if(5===b)return a.P?a.P(c,d,e,g,h):a.P?a.P(c,d,e,g,h):a.call(null,c,d,e,g,h);var k=E(l),m=F(l);
if(6===b)return a.va?a.va(c,d,e,g,h,k):a.va?a.va(c,d,e,g,h,k):a.call(null,c,d,e,g,h,k);var l=E(m),n=F(m);if(7===b)return a.wa?a.wa(c,d,e,g,h,k,l):a.wa?a.wa(c,d,e,g,h,k,l):a.call(null,c,d,e,g,h,k,l);var m=E(n),p=F(n);if(8===b)return a.xa?a.xa(c,d,e,g,h,k,l,m):a.xa?a.xa(c,d,e,g,h,k,l,m):a.call(null,c,d,e,g,h,k,l,m);var n=E(p),q=F(p);if(9===b)return a.ya?a.ya(c,d,e,g,h,k,l,m,n):a.ya?a.ya(c,d,e,g,h,k,l,m,n):a.call(null,c,d,e,g,h,k,l,m,n);var p=E(q),t=F(q);if(10===b)return a.ka?a.ka(c,d,e,g,h,k,l,m,n,
p):a.ka?a.ka(c,d,e,g,h,k,l,m,n,p):a.call(null,c,d,e,g,h,k,l,m,n,p);var q=E(t),u=F(t);if(11===b)return a.la?a.la(c,d,e,g,h,k,l,m,n,p,q):a.la?a.la(c,d,e,g,h,k,l,m,n,p,q):a.call(null,c,d,e,g,h,k,l,m,n,p,q);var t=E(u),w=F(u);if(12===b)return a.ma?a.ma(c,d,e,g,h,k,l,m,n,p,q,t):a.ma?a.ma(c,d,e,g,h,k,l,m,n,p,q,t):a.call(null,c,d,e,g,h,k,l,m,n,p,q,t);var u=E(w),A=F(w);if(13===b)return a.na?a.na(c,d,e,g,h,k,l,m,n,p,q,t,u):a.na?a.na(c,d,e,g,h,k,l,m,n,p,q,t,u):a.call(null,c,d,e,g,h,k,l,m,n,p,q,t,u);var w=E(A),
B=F(A);if(14===b)return a.oa?a.oa(c,d,e,g,h,k,l,m,n,p,q,t,u,w):a.oa?a.oa(c,d,e,g,h,k,l,m,n,p,q,t,u,w):a.call(null,c,d,e,g,h,k,l,m,n,p,q,t,u,w);var A=E(B),H=F(B);if(15===b)return a.pa?a.pa(c,d,e,g,h,k,l,m,n,p,q,t,u,w,A):a.pa?a.pa(c,d,e,g,h,k,l,m,n,p,q,t,u,w,A):a.call(null,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A);var B=E(H),K=F(H);if(16===b)return a.qa?a.qa(c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B):a.qa?a.qa(c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B):a.call(null,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B);var H=E(K),ea=F(K);if(17===b)return a.ra?
a.ra(c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,H):a.ra?a.ra(c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,H):a.call(null,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,H);var K=E(ea),Ea=F(ea);if(18===b)return a.sa?a.sa(c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,H,K):a.sa?a.sa(c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,H,K):a.call(null,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,H,K);ea=E(Ea);Ea=F(Ea);if(19===b)return a.ta?a.ta(c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,H,K,ea):a.ta?a.ta(c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,H,K,ea):a.call(null,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,H,K,ea);var y=
E(Ea);F(Ea);if(20===b)return a.ua?a.ua(c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,H,K,ea,y):a.ua?a.ua(c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,H,K,ea,y):a.call(null,c,d,e,g,h,k,l,m,n,p,q,t,u,w,A,B,H,K,ea,y);throw Error("Only up to 20 arguments supported on functions");}
function kc(){switch(arguments.length){case 2:return Tc(arguments[0],arguments[1]);case 3:return Uc(arguments[0],arguments[1],arguments[2]);case 4:var a;a=arguments[0];var b=R(arguments[1],R(arguments[2],arguments[3])),c=a.V;if(a.N){var d=Qc(b,c+1);a=d<=c?Sc(a,d,b):a.N(b)}else a=a.apply(a,Pc(b));return a;case 5:return Vc(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);default:return a=arguments[0],b=R(arguments[1],R(arguments[2],R(arguments[3],R(arguments[4],Rc(new M(Array.prototype.slice.call(arguments,
5),0)))))),c=a.V,a.N?(d=Qc(b,c+1),a=d<=c?Sc(a,d,b):a.N(b)):a=a.apply(a,Pc(b)),a}}function Tc(a,b){var c=a.V;if(a.N){var d=Qc(b,c+1);return d<=c?Sc(a,d,b):a.N(b)}return a.apply(a,Pc(b))}function Uc(a,b,c){b=R(b,c);c=a.V;if(a.N){var d=Qc(b,c+1);return d<=c?Sc(a,d,b):a.N(b)}return a.apply(a,Pc(b))}function Vc(a,b,c,d,e){b=R(b,R(c,R(d,e)));c=a.V;return a.N?(d=Qc(b,c+1),d<=c?Sc(a,d,b):a.N(b)):a.apply(a,Pc(b))}
function Wc(a,b){for(;;){if(null==L(b))return!0;var c;c=N(b);c=a.f?a.f(c):a.call(null,c);if(v(c)){c=a;var d=O(b);a=c;b=d}else return!1}}function Xc(a,b,c,d){this.state=a;this.m=b;this.Db=c;this.kb=d;this.u=16386;this.h=6455296}f=Xc.prototype;f.equiv=function(a){return this.o(null,a)};f.o=function(a,b){return this===b};f.H=function(){return this.m};
f.ib=function(a,b,c){for(var d=L(this.kb),e=null,g=0,h=0;;)if(h<g){a=e.J(null,h);var k=T(a,0);a=T(a,1);var l=b,m=c;a.A?a.A(k,this,l,m):a.call(null,k,this,l,m);h+=1}else if(a=L(d))d=a,oc(d)?(e=qb(d),d=rb(d),a=e,g=S(e),e=a):(a=N(d),k=T(a,0),a=T(a,1),e=k,g=b,h=c,a.A?a.A(e,this,g,h):a.call(null,e,this,g,h),d=O(d),e=null,g=0),h=0;else return null};f.C=function(){return this[ba]||(this[ba]=++ca)};
function Yc(){switch(arguments.length){case 1:return $c(arguments[0]);default:var a=arguments[0],b=new M(Array.prototype.slice.call(arguments,1),0),c=sc(b)?Tc(ad,b):b,b=ec(c,ua),c=ec(c,bd);return new Xc(a,b,c,null)}}function $c(a){return new Xc(a,null,null,null)}
function cd(a,b){if(a instanceof Xc){var c=a.Db;if(null!=c&&!v(c.f?c.f(b):c.call(null,b)))throw Error([C("Assert failed: "),C("Validator rejected reference state"),C("\n"),C(function(){var a=Ec(new Ib(null,"validate","validate",1439230700,null),new Ib(null,"new-value","new-value",-1567397401,null));return dd.f?dd.f(a):dd.call(null,a)}())].join(""));c=a.state;a.state=b;null!=a.kb&&ib(a,c,b);return b}return tb(a,b)}
var ed=function ed(){switch(arguments.length){case 2:return ed.c(arguments[0],arguments[1]);case 3:return ed.i(arguments[0],arguments[1],arguments[2]);case 4:return ed.A(arguments[0],arguments[1],arguments[2],arguments[3]);default:return ed.w(arguments[0],arguments[1],arguments[2],arguments[3],new M(Array.prototype.slice.call(arguments,4),0))}};ed.c=function(a,b){var c;a instanceof Xc?(c=a.state,c=b.f?b.f(c):b.call(null,c),c=cd(a,c)):c=J.c(a,b);return c};
ed.i=function(a,b,c){if(a instanceof Xc){var d=a.state;b=b.c?b.c(d,c):b.call(null,d,c);a=cd(a,b)}else a=J.i(a,b,c);return a};ed.A=function(a,b,c,d){if(a instanceof Xc){var e=a.state;b=b.i?b.i(e,c,d):b.call(null,e,c,d);a=cd(a,b)}else a=J.A(a,b,c,d);return a};ed.w=function(a,b,c,d,e){return a instanceof Xc?cd(a,Vc(b,a.state,c,d,e)):J.P(a,b,c,d,e)};ed.N=function(a){var b=N(a),c=O(a);a=N(c);var d=O(c),c=N(d),e=O(d),d=N(e),e=O(e);return ed.w(b,a,c,d,e)};ed.V=4;
var V=function V(){switch(arguments.length){case 1:return V.f(arguments[0]);case 2:return V.c(arguments[0],arguments[1]);case 3:return V.i(arguments[0],arguments[1],arguments[2]);case 4:return V.A(arguments[0],arguments[1],arguments[2],arguments[3]);default:return V.w(arguments[0],arguments[1],arguments[2],arguments[3],new M(Array.prototype.slice.call(arguments,4),0))}};
V.f=function(a){return function(b){return function(){function c(c,d){var e=a.f?a.f(d):a.call(null,d);return b.c?b.c(c,e):b.call(null,c,e)}function d(a){return b.f?b.f(a):b.call(null,a)}function e(){return b.D?b.D():b.call(null)}var g=null,h=function(){function c(a,b,e){var g=null;if(2<arguments.length){for(var g=0,h=Array(arguments.length-2);g<h.length;)h[g]=arguments[g+2],++g;g=new M(h,0)}return d.call(this,a,b,g)}function d(c,e,g){e=Uc(a,e,g);return b.c?b.c(c,e):b.call(null,c,e)}c.V=2;c.N=function(a){var b=
N(a);a=O(a);var c=N(a);a=Jb(a);return d(b,c,a)};c.w=d;return c}(),g=function(a,b,g){switch(arguments.length){case 0:return e.call(this);case 1:return d.call(this,a);case 2:return c.call(this,a,b);default:var n=null;if(2<arguments.length){for(var n=0,p=Array(arguments.length-2);n<p.length;)p[n]=arguments[n+2],++n;n=new M(p,0)}return h.w(a,b,n)}throw Error("Invalid arity: "+arguments.length);};g.V=2;g.N=h.N;g.D=e;g.f=d;g.c=c;g.w=h.w;return g}()}};
V.c=function(a,b){return new Ic(null,function(){var c=L(b);if(c){if(oc(c)){for(var d=qb(c),e=S(d),g=new Kc(Array(e),0),h=0;;)if(h<e)Oc(g,function(){var b=D.c(d,h);return a.f?a.f(b):a.call(null,b)}()),h+=1;else break;return Nc(g.ca(),V.c(a,rb(c)))}return R(function(){var b=N(c);return a.f?a.f(b):a.call(null,b)}(),V.c(a,Jb(c)))}return null},null,null)};
V.i=function(a,b,c){return new Ic(null,function(){var d=L(b),e=L(c);if(d&&e){var g=R,h;h=N(d);var k=N(e);h=a.c?a.c(h,k):a.call(null,h,k);d=g(h,V.i(a,Jb(d),Jb(e)))}else d=null;return d},null,null)};V.A=function(a,b,c,d){return new Ic(null,function(){var e=L(b),g=L(c),h=L(d);if(e&&g&&h){var k=R,l;l=N(e);var m=N(g),n=N(h);l=a.i?a.i(l,m,n):a.call(null,l,m,n);e=k(l,V.A(a,Jb(e),Jb(g),Jb(h)))}else e=null;return e},null,null)};
V.w=function(a,b,c,d,e){var g=function k(a){return new Ic(null,function(){var b=V.c(L,a);return Wc(yc,b)?R(V.c(N,b),k(V.c(Jb,b))):null},null,null)};return V.c(function(){return function(b){return Tc(a,b)}}(g),g(bc.w(e,d,ac([c,b],0))))};V.N=function(a){var b=N(a),c=O(a);a=N(c);var d=O(c),c=N(d),e=O(d),d=N(e),e=O(e);return V.w(b,a,c,d,e)};V.V=4;function fd(a,b){this.v=a;this.a=b}
function gd(a){return new fd(a,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null])}function hd(a){a=a.g;return 32>a?0:a-1>>>5<<5}function id(a,b,c){for(;;){if(0===b)return c;var d=gd(a);d.a[0]=c;c=d;b-=5}}var jd=function jd(b,c,d,e){var g=new fd(d.v,Ba(d.a)),h=b.g-1>>>c&31;5===c?g.a[h]=e:(d=d.a[h],b=null!=d?jd(b,c-5,d,e):id(null,c-5,e),g.a[h]=b);return g};
function kd(a,b){throw Error([C("No item "),C(a),C(" in vector of length "),C(b)].join(""));}function ld(a,b){if(b>=hd(a))return a.Z;for(var c=a.root,d=a.shift;;)if(0<d)var e=d-5,c=c.a[b>>>d&31],d=e;else return c.a}function md(a,b){return 0<=b&&b<a.g?ld(a,b):kd(b,a.g)}var nd=function nd(b,c,d,e,g){var h=new fd(d.v,Ba(d.a));if(0===c)h.a[e&31]=g;else{var k=e>>>c&31;b=nd(b,c-5,d.a[k],e,g);h.a[k]=b}return h};function od(a,b,c,d,e,g){this.j=a;this.Ya=b;this.a=c;this.Aa=d;this.start=e;this.end=g}
od.prototype.Xa=function(){return this.j<this.end};od.prototype.next=function(){32===this.j-this.Ya&&(this.a=ld(this.Aa,this.j),this.Ya+=32);var a=this.a[this.j&31];this.j+=1;return a};function X(a,b,c,d,e,g){this.m=a;this.g=b;this.shift=c;this.root=d;this.Z=e;this.l=g;this.h=167668511;this.u=8196}f=X.prototype;f.toString=function(){return wb(this)};f.equiv=function(a){return this.o(null,a)};f.R=function(a,b){return G.i(this,b,null)};f.F=function(a,b,c){return"number"===typeof b?D.i(this,b,c):c};
f.J=function(a,b){return md(this,b)[b&31]};f.aa=function(a,b,c){return 0<=b&&b<this.g?ld(this,b)[b&31]:c};f.fb=function(a,b,c){if(0<=b&&b<this.g)return hd(this)<=b?(a=Ba(this.Z),a[b&31]=c,new X(this.m,this.g,this.shift,this.root,a,null)):new X(this.m,this.g,this.shift,nd(this,this.shift,this.root,b,c),this.Z,null);if(b===this.g)return Ha(this,c);throw Error([C("Index "),C(b),C(" out of bounds  [0,"),C(this.g),C("]")].join(""));};
f.Na=function(){var a=this.g;return new od(0,0,0<S(this)?ld(this,0):null,this,0,a)};f.H=function(){return this.m};f.W=function(){return this.g};f.cb=function(){return D.c(this,0)};f.eb=function(){return D.c(this,1)};f.C=function(){var a=this.l;return null!=a?a:this.l=a=Nb(this)};f.o=function(a,b){if(b instanceof X)if(this.g===S(b))for(var c=ub(this),d=ub(b);;)if(v(c.Xa())){var e=c.next(),g=d.next();if(!P.c(e,g))return!1}else return!0;else return!1;else return Zb(this,b)};
f.Ra=function(){var a=this;return new pd(a.g,a.shift,function(){var b=a.root;return qd.f?qd.f(b):qd.call(null,b)}(),function(){var b=a.Z;return rd.f?rd.f(b):rd.call(null,b)}())};f.S=function(a,b){return Rb(this,b)};f.T=function(a,b,c){a=0;for(var d=c;;)if(a<this.g){var e=ld(this,a);c=e.length;a:for(var g=0;;)if(g<c)var h=e[g],d=b.c?b.c(d,h):b.call(null,d,h),g=g+1;else{e=d;break a}a+=c;d=e}else return d};
f.Ma=function(a,b,c){if("number"===typeof b)return Ua(this,b,c);throw Error("Vector's key for assoc must be a number.");};f.L=function(){if(0===this.g)return null;if(32>=this.g)return new M(this.Z,0);var a;a:{a=this.root;for(var b=this.shift;;)if(0<b)b-=5,a=a.a[0];else{a=a.a;break a}}return sd?sd(this,a,0,0):td.call(null,this,a,0,0)};f.M=function(a,b){return new X(b,this.g,this.shift,this.root,this.Z,this.l)};
f.I=function(a,b){if(32>this.g-hd(this)){for(var c=this.Z.length,d=Array(c+1),e=0;;)if(e<c)d[e]=this.Z[e],e+=1;else break;d[c]=b;return new X(this.m,this.g+1,this.shift,this.root,d,null)}c=(d=this.g>>>5>1<<this.shift)?this.shift+5:this.shift;d?(d=gd(null),d.a[0]=this.root,e=id(null,this.shift,new fd(null,this.Z)),d.a[1]=e):d=jd(this,this.shift,this.root,new fd(null,this.Z));return new X(this.m,this.g+1,c,d,[b],null)};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.J(null,c);case 3:return this.aa(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.c=function(a,c){return this.J(null,c)};a.i=function(a,c,d){return this.aa(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ba(b)))};f.f=function(a){return this.J(null,a)};f.c=function(a,b){return this.aa(null,a,b)};
var ud=new fd(null,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]),cc=new X(null,0,5,ud,[],Ob);X.prototype[Aa]=function(){return Q(this)};function vd(a,b,c,d,e,g){this.ea=a;this.node=b;this.j=c;this.O=d;this.m=e;this.l=g;this.h=32375020;this.u=1536}f=vd.prototype;f.toString=function(){return wb(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.m};
f.Y=function(){if(this.O+1<this.node.length){var a;a=this.ea;var b=this.node,c=this.j,d=this.O+1;a=sd?sd(a,b,c,d):td.call(null,a,b,c,d);return null==a?null:a}return sb(this)};f.C=function(){var a=this.l;return null!=a?a:this.l=a=Nb(this)};f.o=function(a,b){return Zb(this,b)};f.S=function(a,b){var c;c=this.ea;var d=this.j+this.O,e=S(this.ea);c=wd?wd(c,d,e):xd.call(null,c,d,e);return Rb(c,b)};
f.T=function(a,b,c){a=this.ea;var d=this.j+this.O,e=S(this.ea);a=wd?wd(a,d,e):xd.call(null,a,d,e);return Sb(a,b,c)};f.U=function(){return this.node[this.O]};f.$=function(){if(this.O+1<this.node.length){var a;a=this.ea;var b=this.node,c=this.j,d=this.O+1;a=sd?sd(a,b,c,d):td.call(null,a,b,c,d);return null==a?Kb:a}return rb(this)};f.L=function(){return this};f.ab=function(){var a=this.node;return new Lc(a,this.O,a.length)};
f.bb=function(){var a=this.j+this.node.length;if(a<Ga(this.ea)){var b=this.ea,c=ld(this.ea,a);return sd?sd(b,c,a,0):td.call(null,b,c,a,0)}return Kb};f.M=function(a,b){var c=this.ea,d=this.node,e=this.j,g=this.O;return yd?yd(c,d,e,g,b):td.call(null,c,d,e,g,b)};f.I=function(a,b){return R(b,this)};f.$a=function(){var a=this.j+this.node.length;if(a<Ga(this.ea)){var b=this.ea,c=ld(this.ea,a);return sd?sd(b,c,a,0):td.call(null,b,c,a,0)}return null};vd.prototype[Aa]=function(){return Q(this)};
function td(){switch(arguments.length){case 3:var a=arguments[0],b=arguments[1],c=arguments[2];return new vd(a,md(a,b),b,c,null,null);case 4:return sd(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return yd(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));}}function sd(a,b,c,d){return new vd(a,b,c,d,null,null)}function yd(a,b,c,d,e){return new vd(a,b,c,d,e,null)}
function zd(a,b,c,d,e){this.m=a;this.Aa=b;this.start=c;this.end=d;this.l=e;this.h=167666463;this.u=8192}f=zd.prototype;f.toString=function(){return wb(this)};f.equiv=function(a){return this.o(null,a)};f.R=function(a,b){return G.i(this,b,null)};f.F=function(a,b,c){return"number"===typeof b?D.i(this,b,c):c};f.J=function(a,b){return 0>b||this.end<=this.start+b?kd(b,this.end-this.start):D.c(this.Aa,this.start+b)};f.aa=function(a,b,c){return 0>b||this.end<=this.start+b?c:D.i(this.Aa,this.start+b,c)};
f.fb=function(a,b,c){var d=this.start+b;a=this.m;c=gc.i(this.Aa,d,c);b=this.start;var e=this.end,d=d+1,d=e>d?e:d;return Ad.P?Ad.P(a,c,b,d,null):Ad.call(null,a,c,b,d,null)};f.H=function(){return this.m};f.W=function(){return this.end-this.start};f.C=function(){var a=this.l;return null!=a?a:this.l=a=Nb(this)};f.o=function(a,b){return Zb(this,b)};f.S=function(a,b){return Rb(this,b)};f.T=function(a,b,c){return Sb(this,b,c)};
f.Ma=function(a,b,c){if("number"===typeof b)return Ua(this,b,c);throw Error("Subvec's key for assoc must be a number.");};f.L=function(){var a=this;return function(b){return function d(e){return e===a.end?null:R(D.c(a.Aa,e),new Ic(null,function(){return function(){return d(e+1)}}(b),null,null))}}(this)(a.start)};f.M=function(a,b){var c=this.Aa,d=this.start,e=this.end,g=this.l;return Ad.P?Ad.P(b,c,d,e,g):Ad.call(null,b,c,d,e,g)};
f.I=function(a,b){var c=this.m,d=Ua(this.Aa,this.end,b),e=this.start,g=this.end+1;return Ad.P?Ad.P(c,d,e,g,null):Ad.call(null,c,d,e,g,null)};f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.J(null,c);case 3:return this.aa(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.c=function(a,c){return this.J(null,c)};a.i=function(a,c,d){return this.aa(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ba(b)))};
f.f=function(a){return this.J(null,a)};f.c=function(a,b){return this.aa(null,a,b)};zd.prototype[Aa]=function(){return Q(this)};function Ad(a,b,c,d,e){for(;;)if(b instanceof zd)c=b.start+c,d=b.start+d,b=b.Aa;else{var g=S(b);if(0>c||0>d||c>g||d>g)throw Error("Index out of bounds");return new zd(a,b,c,d,e)}}
function xd(){switch(arguments.length){case 2:var a=arguments[0];return wd(a,arguments[1],S(a));case 3:return wd(arguments[0],arguments[1],arguments[2]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));}}function wd(a,b,c){return Ad(null,a,b,c,null)}function Bd(a,b){return a===b.v?b:new fd(a,Ba(b.a))}function qd(a){return new fd({},Ba(a.a))}
function rd(a){var b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];qc(a,0,b,0,a.length);return b}var Cd=function Cd(b,c,d,e){d=Bd(b.root.v,d);var g=b.g-1>>>c&31;if(5===c)b=e;else{var h=d.a[g];b=null!=h?Cd(b,c-5,h,e):id(b.root.v,c-5,e)}d.a[g]=b;return d};function pd(a,b,c,d){this.g=a;this.shift=b;this.root=c;this.Z=d;this.u=88;this.h=275}f=pd.prototype;
f.Va=function(a,b){if(this.root.v){if(32>this.g-hd(this))this.Z[this.g&31]=b;else{var c=new fd(this.root.v,this.Z),d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];d[0]=b;this.Z=d;if(this.g>>>5>1<<this.shift){var d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],e=this.shift+
5;d[0]=this.root;d[1]=id(this.root.v,this.shift,c);this.root=new fd(this.root.v,d);this.shift=e}else this.root=Cd(this,this.shift,this.root,c)}this.g+=1;return this}throw Error("conj! after persistent!");};f.Wa=function(){if(this.root.v){this.root.v=null;var a=this.g-hd(this),b=Array(a);qc(this.Z,0,b,0,a);return new X(null,this.g,this.shift,this.root,b,null)}throw Error("persistent! called twice");};
f.Oa=function(a,b,c){if("number"===typeof b)return ob(this,b,c);throw Error("TransientVector's key for assoc! must be a number.");};
f.hb=function(a,b,c){var d=this;if(d.root.v){if(0<=b&&b<d.g)return hd(this)<=b?d.Z[b&31]=c:(a=function(){return function g(a,k){var l=Bd(d.root.v,k);if(0===a)l.a[b&31]=c;else{var m=b>>>a&31,n=g(a-5,l.a[m]);l.a[m]=n}return l}}(this).call(null,d.shift,d.root),d.root=a),this;if(b===d.g)return kb(this,c);throw Error([C("Index "),C(b),C(" out of bounds for TransientVector of length"),C(d.g)].join(""));}throw Error("assoc! after persistent!");};
f.W=function(){if(this.root.v)return this.g;throw Error("count after persistent!");};f.J=function(a,b){if(this.root.v)return md(this,b)[b&31];throw Error("nth after persistent!");};f.aa=function(a,b,c){return 0<=b&&b<this.g?D.c(this,b):c};f.R=function(a,b){return G.i(this,b,null)};f.F=function(a,b,c){return"number"===typeof b?D.i(this,b,c):c};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.R(null,c);case 3:return this.F(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.c=function(a,c){return this.R(null,c)};a.i=function(a,c,d){return this.F(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ba(b)))};f.f=function(a){return this.R(null,a)};f.c=function(a,b){return this.F(null,a,b)};function Dd(){this.h=2097152;this.u=0}
Dd.prototype.equiv=function(a){return this.o(null,a)};Dd.prototype.o=function(){return!1};var Ed=new Dd;function Fd(a,b){return tc(mc(b)?S(a)===S(b)?Wc(yc,V.c(function(a){return P.c(fc(b,N(a),Ed),N(O(a)))},a)):null:null)}function Gd(a){this.s=a}Gd.prototype.next=function(){if(null!=this.s){var a=N(this.s),b=T(a,0),a=T(a,1);this.s=O(this.s);return{value:[b,a],done:!1}}return{value:null,done:!0}};function Hd(a){return new Gd(L(a))}
function Id(a,b){var c;if(b instanceof U)a:{c=a.length;for(var d=b.Ca,e=0;;){if(c<=e){c=-1;break a}var g=a[e];if(g instanceof U&&d===g.Ca){c=e;break a}e+=2}}else if(c="string"==typeof b,v(v(c)?c:"number"===typeof b))a:for(c=a.length,d=0;;){if(c<=d){c=-1;break a}if(b===a[d]){c=d;break a}d+=2}else if(b instanceof Ib)a:for(c=a.length,d=b.Ea,e=0;;){if(c<=e){c=-1;break a}g=a[e];if(g instanceof Ib&&d===g.Ea){c=e;break a}e+=2}else if(null==b)a:for(c=a.length,d=0;;){if(c<=d){c=-1;break a}if(null==a[d]){c=
d;break a}d+=2}else a:for(c=a.length,d=0;;){if(c<=d){c=-1;break a}if(P.c(b,a[d])){c=d;break a}d+=2}return c}function Jd(a,b,c){this.a=a;this.j=b;this.ba=c;this.h=32374990;this.u=0}f=Jd.prototype;f.toString=function(){return wb(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.ba};f.Y=function(){return this.j<this.a.length-2?new Jd(this.a,this.j+2,this.ba):null};f.W=function(){return(this.a.length-this.j)/2};f.C=function(){return Nb(this)};
f.o=function(a,b){return Zb(this,b)};f.S=function(a,b){return uc(b,this)};f.T=function(a,b,c){return xc(b,c,this)};f.U=function(){return new X(null,2,5,ud,[this.a[this.j],this.a[this.j+1]],null)};f.$=function(){return this.j<this.a.length-2?new Jd(this.a,this.j+2,this.ba):Kb};f.L=function(){return this};f.M=function(a,b){return new Jd(this.a,this.j,b)};f.I=function(a,b){return R(b,this)};Jd.prototype[Aa]=function(){return Q(this)};function Kd(a,b,c){this.a=a;this.j=b;this.g=c}
Kd.prototype.Xa=function(){return this.j<this.g};Kd.prototype.next=function(){var a=new X(null,2,5,ud,[this.a[this.j],this.a[this.j+1]],null);this.j+=2;return a};function qa(a,b,c,d){this.m=a;this.g=b;this.a=c;this.l=d;this.h=16647951;this.u=8196}f=qa.prototype;f.toString=function(){return wb(this)};f.equiv=function(a){return this.o(null,a)};f.keys=function(){return Q(Ld.f?Ld.f(this):Ld.call(null,this))};f.entries=function(){return Hd(L(this))};
f.values=function(){return Q(Md.f?Md.f(this):Md.call(null,this))};f.has=function(a){return fc(this,a,rc)===rc?!1:!0};f.get=function(a,b){return this.F(null,a,b)};f.forEach=function(a){for(var b=L(this),c=null,d=0,e=0;;)if(e<d){var g=c.J(null,e),h=T(g,0),g=T(g,1);a.c?a.c(g,h):a.call(null,g,h);e+=1}else if(b=L(b))oc(b)?(c=qb(b),b=rb(b),h=c,d=S(c),c=h):(c=N(b),h=T(c,0),c=g=T(c,1),a.c?a.c(c,h):a.call(null,c,h),b=O(b),c=null,d=0),e=0;else return null};f.R=function(a,b){return G.i(this,b,null)};
f.F=function(a,b,c){a=Id(this.a,b);return-1===a?c:this.a[a+1]};f.Na=function(){return new Kd(this.a,0,2*this.g)};f.H=function(){return this.m};f.W=function(){return this.g};f.C=function(){var a=this.l;return null!=a?a:this.l=a=Pb(this)};f.o=function(a,b){if(b&&(b.h&1024||b.qb)){var c=this.a.length;if(this.g===b.W(null))for(var d=0;;)if(d<c){var e=b.F(null,this.a[d],rc);if(e!==rc)if(P.c(this.a[d+1],e))d+=2;else return!1;else return!1}else return!0;else return!1}else return Fd(this,b)};
f.Ra=function(){return new Nd({},this.a.length,Ba(this.a))};f.S=function(a,b){return uc(b,this)};f.T=function(a,b,c){return xc(b,c,this)};
f.Ma=function(a,b,c){a=Id(this.a,b);if(-1===a){if(this.g<Od){a=this.a;for(var d=a.length,e=Array(d+2),g=0;;)if(g<d)e[g]=a[g],g+=1;else break;e[d]=b;e[d+1]=c;return new qa(this.m,this.g+1,e,null)}a=hc;null!=a?a&&(a.u&4||a.Fb)?(d=vc(kb,jb(a),this),d=lb(d),a=lc(a),a=ic(d)&&!(d?d.h&262144||d.Kb||(d.h?0:x(Xa,d)):x(Xa,d))?new jc(d,a):null==d?null:Ya(d,a)):a=vc(Ha,a,this):a=vc(bc,Kb,this);return Ya(Na(a,b,c),this.m)}if(c===this.a[a+1])return this;b=Ba(this.a);b[a+1]=c;return new qa(this.m,this.g,b,null)};
f.L=function(){var a=this.a;return 0<=a.length-2?new Jd(a,0,null):null};f.M=function(a,b){return new qa(b,this.g,this.a,this.l)};f.I=function(a,b){if(nc(b))return Na(this,D.c(b,0),D.c(b,1));for(var c=this,d=L(b);;){if(null==d)return c;var e=N(d);if(nc(e))c=Na(c,D.c(e,0),D.c(e,1)),d=O(d);else throw Error("conj on a map takes map entries or seqables of map entries");}};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.R(null,c);case 3:return this.F(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.c=function(a,c){return this.R(null,c)};a.i=function(a,c,d){return this.F(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ba(b)))};f.f=function(a){return this.R(null,a)};f.c=function(a,b){return this.F(null,a,b)};var Od=8;qa.prototype[Aa]=function(){return Q(this)};
function Nd(a,b,c){this.Ja=a;this.La=b;this.a=c;this.h=258;this.u=56}f=Nd.prototype;f.W=function(){if(v(this.Ja))return zc(this.La);throw Error("count after persistent!");};f.R=function(a,b){return G.i(this,b,null)};f.F=function(a,b,c){if(v(this.Ja))return a=Id(this.a,b),-1===a?c:this.a[a+1];throw Error("lookup after persistent!");};
f.Va=function(a,b){if(v(this.Ja)){if(b?b.h&2048||b.rb||(b.h?0:x(Pa,b)):x(Pa,b))return mb(this,Pd.f?Pd.f(b):Pd.call(null,b),Rd.f?Rd.f(b):Rd.call(null,b));for(var c=L(b),d=this;;){var e=N(c);if(v(e))var g=e,c=O(c),d=mb(d,function(){var a=g;return Pd.f?Pd.f(a):Pd.call(null,a)}(),function(){var a=g;return Rd.f?Rd.f(a):Rd.call(null,a)}());else return d}}else throw Error("conj! after persistent!");};
f.Wa=function(){if(v(this.Ja))return this.Ja=!1,new qa(null,zc(this.La),this.a,null);throw Error("persistent! called twice");};f.Oa=function(a,b,c){if(v(this.Ja)){a=Id(this.a,b);if(-1===a){if(this.La+2<=2*Od)return this.La+=2,this.a.push(b),this.a.push(c),this;a=this.La;var d=this.a;a=Sd.c?Sd.c(a,d):Sd.call(null,a,d);return mb(a,b,c)}c!==this.a[a+1]&&(this.a[a+1]=c);return this}throw Error("assoc! after persistent!");};
function Sd(a,b){for(var c=jb(hc),d=0;;)if(d<a)c=mb(c,b[d],b[d+1]),d+=2;else return c}function Td(){this.ja=!1}function Ud(a,b){return a===b?!0:a===b||a instanceof U&&b instanceof U&&a.Ca===b.Ca?!0:P.c(a,b)}function Vd(a,b,c){a=Ba(a);a[b]=c;return a}function Wd(a,b,c,d){a=a.Ga(b);a.a[c]=d;return a}function Xd(a,b,c){this.v=a;this.G=b;this.a=c}f=Xd.prototype;f.Ga=function(a){if(a===this.v)return this;var b=Bc(this.G),c=Array(0>b?4:2*(b+1));qc(this.a,0,c,0,2*b);return new Xd(a,this.G,c)};
f.Pa=function(){var a=this.a;return Yd?Yd(a):Zd.call(null,a)};f.Ha=function(a,b,c,d){var e=1<<(b>>>a&31);if(0===(this.G&e))return d;var g=Bc(this.G&e-1),e=this.a[2*g],g=this.a[2*g+1];return null==e?g.Ha(a+5,b,c,d):Ud(c,e)?g:d};
f.ha=function(a,b,c,d,e,g){var h=1<<(c>>>b&31),k=Bc(this.G&h-1);if(0===(this.G&h)){var l=Bc(this.G);if(2*l<this.a.length){a=this.Ga(a);b=a.a;g.ja=!0;a:for(c=2*(l-k),g=2*k+(c-1),l=2*(k+1)+(c-1);;){if(0===c)break a;b[l]=b[g];--l;--c;--g}b[2*k]=d;b[2*k+1]=e;a.G|=h;return a}if(16<=l){k=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];k[c>>>b&31]=$d.ha(a,b+5,c,d,e,g);for(e=d=0;;)if(32>d)0!==
(this.G>>>d&1)&&(k[d]=null!=this.a[e]?$d.ha(a,b+5,Gb(this.a[e]),this.a[e],this.a[e+1],g):this.a[e+1],e+=2),d+=1;else break;return new ae(a,l+1,k)}b=Array(2*(l+4));qc(this.a,0,b,0,2*k);b[2*k]=d;b[2*k+1]=e;qc(this.a,2*k,b,2*(k+1),2*(l-k));g.ja=!0;a=this.Ga(a);a.a=b;a.G|=h;return a}l=this.a[2*k];h=this.a[2*k+1];if(null==l)return l=h.ha(a,b+5,c,d,e,g),l===h?this:Wd(this,a,2*k+1,l);if(Ud(d,l))return e===h?this:Wd(this,a,2*k+1,e);g.ja=!0;g=b+5;d=be?be(a,g,l,h,c,d,e):ce.call(null,a,g,l,h,c,d,e);e=2*k;k=
2*k+1;a=this.Ga(a);a.a[e]=null;a.a[k]=d;return a};
f.ga=function(a,b,c,d,e){var g=1<<(b>>>a&31),h=Bc(this.G&g-1);if(0===(this.G&g)){var k=Bc(this.G);if(16<=k){h=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];h[b>>>a&31]=$d.ga(a+5,b,c,d,e);for(d=c=0;;)if(32>c)0!==(this.G>>>c&1)&&(h[c]=null!=this.a[d]?$d.ga(a+5,Gb(this.a[d]),this.a[d],this.a[d+1],e):this.a[d+1],d+=2),c+=1;else break;return new ae(null,k+1,h)}a=Array(2*(k+1));qc(this.a,
0,a,0,2*h);a[2*h]=c;a[2*h+1]=d;qc(this.a,2*h,a,2*(h+1),2*(k-h));e.ja=!0;return new Xd(null,this.G|g,a)}var l=this.a[2*h],g=this.a[2*h+1];if(null==l)return k=g.ga(a+5,b,c,d,e),k===g?this:new Xd(null,this.G,Vd(this.a,2*h+1,k));if(Ud(c,l))return d===g?this:new Xd(null,this.G,Vd(this.a,2*h+1,d));e.ja=!0;e=this.G;k=this.a;a+=5;a=de?de(a,l,g,b,c,d):ce.call(null,a,l,g,b,c,d);c=2*h;h=2*h+1;d=Ba(k);d[c]=null;d[h]=a;return new Xd(null,e,d)};var $d=new Xd(null,0,[]);
function ae(a,b,c){this.v=a;this.g=b;this.a=c}f=ae.prototype;f.Ga=function(a){return a===this.v?this:new ae(a,this.g,Ba(this.a))};f.Pa=function(){var a=this.a;return ee?ee(a):fe.call(null,a)};f.Ha=function(a,b,c,d){var e=this.a[b>>>a&31];return null!=e?e.Ha(a+5,b,c,d):d};f.ha=function(a,b,c,d,e,g){var h=c>>>b&31,k=this.a[h];if(null==k)return a=Wd(this,a,h,$d.ha(a,b+5,c,d,e,g)),a.g+=1,a;b=k.ha(a,b+5,c,d,e,g);return b===k?this:Wd(this,a,h,b)};
f.ga=function(a,b,c,d,e){var g=b>>>a&31,h=this.a[g];if(null==h)return new ae(null,this.g+1,Vd(this.a,g,$d.ga(a+5,b,c,d,e)));a=h.ga(a+5,b,c,d,e);return a===h?this:new ae(null,this.g,Vd(this.a,g,a))};function ge(a,b,c){b*=2;for(var d=0;;)if(d<b){if(Ud(c,a[d]))return d;d+=2}else return-1}function he(a,b,c,d){this.v=a;this.Ba=b;this.g=c;this.a=d}f=he.prototype;f.Ga=function(a){if(a===this.v)return this;var b=Array(2*(this.g+1));qc(this.a,0,b,0,2*this.g);return new he(a,this.Ba,this.g,b)};
f.Pa=function(){var a=this.a;return Yd?Yd(a):Zd.call(null,a)};f.Ha=function(a,b,c,d){a=ge(this.a,this.g,c);return 0>a?d:Ud(c,this.a[a])?this.a[a+1]:d};
f.ha=function(a,b,c,d,e,g){if(c===this.Ba){b=ge(this.a,this.g,d);if(-1===b){if(this.a.length>2*this.g)return b=2*this.g,c=2*this.g+1,a=this.Ga(a),a.a[b]=d,a.a[c]=e,g.ja=!0,a.g+=1,a;c=this.a.length;b=Array(c+2);qc(this.a,0,b,0,c);b[c]=d;b[c+1]=e;g.ja=!0;d=this.g+1;a===this.v?(this.a=b,this.g=d,a=this):a=new he(this.v,this.Ba,d,b);return a}return this.a[b+1]===e?this:Wd(this,a,b+1,e)}return(new Xd(a,1<<(this.Ba>>>b&31),[null,this,null,null])).ha(a,b,c,d,e,g)};
f.ga=function(a,b,c,d,e){return b===this.Ba?(a=ge(this.a,this.g,c),-1===a?(a=2*this.g,b=Array(a+2),qc(this.a,0,b,0,a),b[a]=c,b[a+1]=d,e.ja=!0,new he(null,this.Ba,this.g+1,b)):P.c(this.a[a],d)?this:new he(null,this.Ba,this.g,Vd(this.a,a+1,d))):(new Xd(null,1<<(this.Ba>>>a&31),[null,this])).ga(a,b,c,d,e)};
function ce(){switch(arguments.length){case 6:return de(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);case 7:return be(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));}}function de(a,b,c,d,e,g){var h=Gb(b);if(h===d)return new he(null,h,2,[b,c,e,g]);var k=new Td;return $d.ga(a,h,b,c,k).ga(a,d,e,g,k)}
function be(a,b,c,d,e,g,h){var k=Gb(c);if(k===e)return new he(null,k,2,[c,d,g,h]);var l=new Td;return $d.ha(a,b,k,c,d,l).ha(a,b,e,g,h,l)}function ie(a,b,c,d,e){this.m=a;this.Da=b;this.j=c;this.s=d;this.l=e;this.h=32374860;this.u=0}f=ie.prototype;f.toString=function(){return wb(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.m};f.C=function(){var a=this.l;return null!=a?a:this.l=a=Nb(this)};f.o=function(a,b){return Zb(this,b)};f.S=function(a,b){return uc(b,this)};
f.T=function(a,b,c){return xc(b,c,this)};f.U=function(){return null==this.s?new X(null,2,5,ud,[this.Da[this.j],this.Da[this.j+1]],null):N(this.s)};f.$=function(){if(null==this.s){var a=this.Da,b=this.j+2;return je?je(a,b,null):Zd.call(null,a,b,null)}var a=this.Da,b=this.j,c=O(this.s);return je?je(a,b,c):Zd.call(null,a,b,c)};f.L=function(){return this};f.M=function(a,b){return new ie(b,this.Da,this.j,this.s,this.l)};f.I=function(a,b){return R(b,this)};ie.prototype[Aa]=function(){return Q(this)};
function Zd(){switch(arguments.length){case 1:return Yd(arguments[0]);case 3:return je(arguments[0],arguments[1],arguments[2]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));}}function Yd(a){return je(a,0,null)}function je(a,b,c){if(null==c)for(c=a.length;;)if(b<c){if(null!=a[b])return new ie(null,a,b,null,null);var d=a[b+1];if(v(d)&&(d=d.Pa(),v(d)))return new ie(null,a,b+2,d,null);b+=2}else return null;else return new ie(null,a,b,c,null)}
function ke(a,b,c,d,e){this.m=a;this.Da=b;this.j=c;this.s=d;this.l=e;this.h=32374860;this.u=0}f=ke.prototype;f.toString=function(){return wb(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.m};f.C=function(){var a=this.l;return null!=a?a:this.l=a=Nb(this)};f.o=function(a,b){return Zb(this,b)};f.S=function(a,b){return uc(b,this)};f.T=function(a,b,c){return xc(b,c,this)};f.U=function(){return N(this.s)};
f.$=function(){var a=this.Da,b=this.j,c=O(this.s);return le?le(null,a,b,c):fe.call(null,null,a,b,c)};f.L=function(){return this};f.M=function(a,b){return new ke(b,this.Da,this.j,this.s,this.l)};f.I=function(a,b){return R(b,this)};ke.prototype[Aa]=function(){return Q(this)};function fe(){switch(arguments.length){case 1:return ee(arguments[0]);case 4:return le(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));}}
function ee(a){return le(null,a,0,null)}function le(a,b,c,d){if(null==d)for(d=b.length;;)if(c<d){var e=b[c];if(v(e)&&(e=e.Pa(),v(e)))return new ke(a,b,c+1,e,null);c+=1}else return null;else return new ke(a,b,c,d,null)}function me(a,b,c,d,e,g){this.m=a;this.g=b;this.root=c;this.da=d;this.fa=e;this.l=g;this.h=16123663;this.u=8196}f=me.prototype;f.toString=function(){return wb(this)};f.equiv=function(a){return this.o(null,a)};f.keys=function(){return Q(Ld.f?Ld.f(this):Ld.call(null,this))};
f.entries=function(){return Hd(L(this))};f.values=function(){return Q(Md.f?Md.f(this):Md.call(null,this))};f.has=function(a){return fc(this,a,rc)===rc?!1:!0};f.get=function(a,b){return this.F(null,a,b)};f.forEach=function(a){for(var b=L(this),c=null,d=0,e=0;;)if(e<d){var g=c.J(null,e),h=T(g,0),g=T(g,1);a.c?a.c(g,h):a.call(null,g,h);e+=1}else if(b=L(b))oc(b)?(c=qb(b),b=rb(b),h=c,d=S(c),c=h):(c=N(b),h=T(c,0),c=g=T(c,1),a.c?a.c(c,h):a.call(null,c,h),b=O(b),c=null,d=0),e=0;else return null};
f.R=function(a,b){return G.i(this,b,null)};f.F=function(a,b,c){return null==b?this.da?this.fa:c:null==this.root?c:this.root.Ha(0,Gb(b),b,c)};f.H=function(){return this.m};f.W=function(){return this.g};f.C=function(){var a=this.l;return null!=a?a:this.l=a=Pb(this)};f.o=function(a,b){return Fd(this,b)};f.Ra=function(){return new ne({},this.root,this.g,this.da,this.fa)};
f.Ma=function(a,b,c){if(null==b)return this.da&&c===this.fa?this:new me(this.m,this.da?this.g:this.g+1,this.root,!0,c,null);a=new Td;b=(null==this.root?$d:this.root).ga(0,Gb(b),b,c,a);return b===this.root?this:new me(this.m,a.ja?this.g+1:this.g,b,this.da,this.fa,null)};f.L=function(){if(0<this.g){var a=null!=this.root?this.root.Pa():null;return this.da?R(new X(null,2,5,ud,[null,this.fa],null),a):a}return null};f.M=function(a,b){return new me(b,this.g,this.root,this.da,this.fa,this.l)};
f.I=function(a,b){if(nc(b))return Na(this,D.c(b,0),D.c(b,1));for(var c=this,d=L(b);;){if(null==d)return c;var e=N(d);if(nc(e))c=Na(c,D.c(e,0),D.c(e,1)),d=O(d);else throw Error("conj on a map takes map entries or seqables of map entries");}};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.R(null,c);case 3:return this.F(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.c=function(a,c){return this.R(null,c)};a.i=function(a,c,d){return this.F(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ba(b)))};f.f=function(a){return this.R(null,a)};f.c=function(a,b){return this.F(null,a,b)};var hc=new me(null,0,null,!1,null,Qb);me.prototype[Aa]=function(){return Q(this)};
function ne(a,b,c,d,e){this.v=a;this.root=b;this.count=c;this.da=d;this.fa=e;this.h=258;this.u=56}function oe(a,b){if(a.v){if(b?b.h&2048||b.rb||(b.h?0:x(Pa,b)):x(Pa,b))return pe(a,Pd.f?Pd.f(b):Pd.call(null,b),Rd.f?Rd.f(b):Rd.call(null,b));for(var c=L(b),d=a;;){var e=N(c);if(v(e))var g=e,c=O(c),d=pe(d,function(){var a=g;return Pd.f?Pd.f(a):Pd.call(null,a)}(),function(){var a=g;return Rd.f?Rd.f(a):Rd.call(null,a)}());else return d}}else throw Error("conj! after persistent");}
function pe(a,b,c){if(a.v){if(null==b)a.fa!==c&&(a.fa=c),a.da||(a.count+=1,a.da=!0);else{var d=new Td;b=(null==a.root?$d:a.root).ha(a.v,0,Gb(b),b,c,d);b!==a.root&&(a.root=b);d.ja&&(a.count+=1)}return a}throw Error("assoc! after persistent!");}f=ne.prototype;f.W=function(){if(this.v)return this.count;throw Error("count after persistent!");};f.R=function(a,b){return null==b?this.da?this.fa:null:null==this.root?null:this.root.Ha(0,Gb(b),b)};
f.F=function(a,b,c){return null==b?this.da?this.fa:c:null==this.root?c:this.root.Ha(0,Gb(b),b,c)};f.Va=function(a,b){return oe(this,b)};f.Wa=function(){var a;if(this.v)this.v=null,a=new me(null,this.count,this.root,this.da,this.fa,null);else throw Error("persistent! called twice");return a};f.Oa=function(a,b,c){return pe(this,b,c)};var ad=function ad(){return ad.w(0<arguments.length?new M(Array.prototype.slice.call(arguments,0),0):null)};
ad.w=function(a){for(var b=L(a),c=jb(hc);;)if(b){a=O(O(b));var d=N(b),b=N(O(b)),c=mb(c,d,b),b=a}else return lb(c)};ad.V=0;ad.N=function(a){return ad.w(L(a))};function qe(a,b){this.X=a;this.ba=b;this.h=32374988;this.u=0}f=qe.prototype;f.toString=function(){return wb(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.ba};f.Y=function(){var a=this.X,a=(a?a.h&128||a.Ta||(a.h?0:x(La,a)):x(La,a))?this.X.Y(null):O(this.X);return null==a?null:new qe(a,this.ba)};f.C=function(){return Nb(this)};
f.o=function(a,b){return Zb(this,b)};f.S=function(a,b){return uc(b,this)};f.T=function(a,b,c){return xc(b,c,this)};f.U=function(){return this.X.U(null).cb()};f.$=function(){var a=this.X,a=(a?a.h&128||a.Ta||(a.h?0:x(La,a)):x(La,a))?this.X.Y(null):O(this.X);return null!=a?new qe(a,this.ba):Kb};f.L=function(){return this};f.M=function(a,b){return new qe(this.X,b)};f.I=function(a,b){return R(b,this)};qe.prototype[Aa]=function(){return Q(this)};function Ld(a){return(a=L(a))?new qe(a,null):null}
function Pd(a){return Qa(a)}function re(a,b){this.X=a;this.ba=b;this.h=32374988;this.u=0}f=re.prototype;f.toString=function(){return wb(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.ba};f.Y=function(){var a=this.X,a=(a?a.h&128||a.Ta||(a.h?0:x(La,a)):x(La,a))?this.X.Y(null):O(this.X);return null==a?null:new re(a,this.ba)};f.C=function(){return Nb(this)};f.o=function(a,b){return Zb(this,b)};f.S=function(a,b){return uc(b,this)};f.T=function(a,b,c){return xc(b,c,this)};
f.U=function(){return this.X.U(null).eb()};f.$=function(){var a=this.X,a=(a?a.h&128||a.Ta||(a.h?0:x(La,a)):x(La,a))?this.X.Y(null):O(this.X);return null!=a?new re(a,this.ba):Kb};f.L=function(){return this};f.M=function(a,b){return new re(this.X,b)};f.I=function(a,b){return R(b,this)};re.prototype[Aa]=function(){return Q(this)};function Md(a){return(a=L(a))?new re(a,null):null}function Rd(a){return Ra(a)}
function Hc(a){if(a&&(a.u&4096||a.tb))return a.name;if("string"===typeof a)return a;throw Error([C("Doesn't support name: "),C(a)].join(""));}function se(a,b,c){this.j=a;this.end=b;this.step=c}se.prototype.Xa=function(){return 0<this.step?this.j<this.end:this.j>this.end};se.prototype.next=function(){var a=this.j;this.j+=this.step;return a};function te(a,b,c,d,e){this.m=a;this.start=b;this.end=c;this.step=d;this.l=e;this.h=32375006;this.u=8192}f=te.prototype;f.toString=function(){return wb(this)};
f.equiv=function(a){return this.o(null,a)};f.J=function(a,b){if(b<Ga(this))return this.start+b*this.step;if(this.start>this.end&&0===this.step)return this.start;throw Error("Index out of bounds");};f.aa=function(a,b,c){return b<Ga(this)?this.start+b*this.step:this.start>this.end&&0===this.step?this.start:c};f.Na=function(){return new se(this.start,this.end,this.step)};f.H=function(){return this.m};
f.Y=function(){return 0<this.step?this.start+this.step<this.end?new te(this.m,this.start+this.step,this.end,this.step,null):null:this.start+this.step>this.end?new te(this.m,this.start+this.step,this.end,this.step,null):null};f.W=function(){var a=eb(this);return v(a)?Math.ceil((this.end-this.start)/this.step):0};f.C=function(){var a=this.l;return null!=a?a:this.l=a=Nb(this)};f.o=function(a,b){return Zb(this,b)};f.S=function(a,b){return Rb(this,b)};
f.T=function(a,b,c){for(a=this.start;;)if(0<this.step?a<this.end:a>this.end){var d=a;c=b.c?b.c(c,d):b.call(null,c,d);a+=this.step}else return c};f.U=function(){return null==eb(this)?null:this.start};f.$=function(){return null!=eb(this)?new te(this.m,this.start+this.step,this.end,this.step,null):Kb};f.L=function(){return 0<this.step?this.start<this.end?this:null:this.start>this.end?this:null};f.M=function(a,b){return new te(b,this.start,this.end,this.step,this.l)};f.I=function(a,b){return R(b,this)};
te.prototype[Aa]=function(){return Q(this)};
function ue(a,b,c,d,e,g,h){var k=la;la=null==la?null:la-1;try{if(null!=la&&0>la)return I(a,"#");I(a,c);if(0===wa.f(g))L(h)&&I(a,function(){var a=ve.f(g);return v(a)?a:"..."}());else{if(L(h)){var l=N(h);b.i?b.i(l,a,g):b.call(null,l,a,g)}for(var m=O(h),n=wa.f(g)-1;;)if(!m||null!=n&&0===n){L(m)&&0===n&&(I(a,d),I(a,function(){var a=ve.f(g);return v(a)?a:"..."}()));break}else{I(a,d);var p=N(m);c=a;h=g;b.i?b.i(p,c,h):b.call(null,p,c,h);var q=O(m);c=n-1;m=q;n=c}}return I(a,e)}finally{la=k}}
function we(a,b){for(var c=L(b),d=null,e=0,g=0;;)if(g<e){var h=d.J(null,g);I(a,h);g+=1}else if(c=L(c))d=c,oc(d)?(c=qb(d),e=rb(d),d=c,h=S(c),c=e,e=h):(h=N(d),I(a,h),c=O(d),d=null,e=0),g=0;else return null}var xe={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"};function ye(a){return[C('"'),C(a.replace(RegExp('[\\\\"\b\f\n\r\t]',"g"),function(a){return xe[a]})),C('"')].join("")}
function ze(a,b,c){if(null==a)return I(b,"nil");if(void 0===a)return I(b,"#\x3cundefined\x3e");if(v(function(){var b=ec(c,ua);return v(b)?(b=a?a.h&131072||a.sb?!0:a.h?!1:x(Va,a):x(Va,a))?lc(a):b:b}())){I(b,"^");var d=lc(a);Z.i?Z.i(d,b,c):Z.call(null,d,b,c);I(b," ")}return null==a?I(b,"nil"):a.Bb?a.Lb(a,b,c):a&&(a.h&2147483648||a.K)?a.B(null,b,c):(null==a?null:a.constructor)===Boolean||"number"===typeof a?I(b,""+C(a)):null!=a&&a.constructor===Object?(I(b,"#js "),d=V.c(function(b){return new X(null,
2,5,ud,[Gc.f(b),a[b]],null)},pc(a)),Ae.A?Ae.A(d,Z,b,c):Ae.call(null,d,Z,b,c)):ya(a)?ue(b,Z,"#js ["," ","]",c,a):v("string"==typeof a)?v(ta.f(c))?I(b,ye(a)):I(b,a):ic(a)?we(b,ac(["#\x3c",""+C(a),"\x3e"],0)):a instanceof Date?(d=function(a,b){for(var c=""+C(a);;)if(S(c)<b)c=[C("0"),C(c)].join("");else return c},we(b,ac(['#inst "',""+C(a.getUTCFullYear()),"-",d(a.getUTCMonth()+1,2),"-",d(a.getUTCDate(),2),"T",d(a.getUTCHours(),2),":",d(a.getUTCMinutes(),2),":",d(a.getUTCSeconds(),2),".",d(a.getUTCMilliseconds(),
3),"-",'00:00"'],0))):v(a instanceof RegExp)?we(b,ac(['#"',a.source,'"'],0)):(a?a.h&2147483648||a.K||(a.h?0:x(gb,a)):x(gb,a))?hb(a,b,c):we(b,ac(["#\x3c",""+C(a),"\x3e"],0))}function Z(a,b,c){var d=Be.f(c);return v(d)?(c=gc.i(c,Ce,ze),d.i?d.i(a,b,c):d.call(null,a,b,c)):ze(a,b,c)}
function dd(){var a=0<arguments.length?new M(Array.prototype.slice.call(arguments,0),0):null,b=oa(),c;(c=null==a)||(c=L(a),c=v(c)?!1:!0);if(c)c="";else{c=C;var d=b,b=new ha;a:{var e=a,a=new vb(b);Z(N(e),a,d);for(var e=L(O(e)),g=null,h=0,k=0;;)if(k<h){var l=g.J(null,k);I(a," ");Z(l,a,d);k+=1}else if(e=L(e))g=e,oc(g)?(e=qb(g),h=rb(g),g=e,l=S(e),e=h,h=l):(l=N(g),I(a," "),Z(l,a,d),e=O(g),g=null,h=0),k=0;else break a}c=""+c(b)}return c}
function Ae(a,b,c,d){return ue(c,function(a,c,d){var k=Qa(a);b.i?b.i(k,c,d):b.call(null,k,c,d);I(c," ");a=Ra(a);return b.i?b.i(a,c,d):b.call(null,a,c,d)},"{",", ","}",d,L(a))}M.prototype.K=!0;M.prototype.B=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};Ic.prototype.K=!0;Ic.prototype.B=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};ie.prototype.K=!0;ie.prototype.B=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};Jd.prototype.K=!0;
Jd.prototype.B=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};vd.prototype.K=!0;vd.prototype.B=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};Fc.prototype.K=!0;Fc.prototype.B=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};me.prototype.K=!0;me.prototype.B=function(a,b,c){return Ae(this,Z,b,c)};ke.prototype.K=!0;ke.prototype.B=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};zd.prototype.K=!0;zd.prototype.B=function(a,b,c){return ue(b,Z,"["," ","]",c,this)};Mc.prototype.K=!0;
Mc.prototype.B=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};Xc.prototype.K=!0;Xc.prototype.B=function(a,b,c){I(b,"#\x3cAtom: ");Z(this.state,b,c);return I(b,"\x3e")};re.prototype.K=!0;re.prototype.B=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};X.prototype.K=!0;X.prototype.B=function(a,b,c){return ue(b,Z,"["," ","]",c,this)};Dc.prototype.K=!0;Dc.prototype.B=function(a,b){return I(b,"()")};qa.prototype.K=!0;qa.prototype.B=function(a,b,c){return Ae(this,Z,b,c)};te.prototype.K=!0;
te.prototype.B=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};qe.prototype.K=!0;qe.prototype.B=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};Cc.prototype.K=!0;Cc.prototype.B=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};function Ee(a){return Math.floor(Math.random()*a)};var ua=new U(null,"meta","meta",1499536964),va=new U(null,"dup","dup",556298533),bd=new U(null,"validator","validator",-1966190681),Fe=new U(null,"pos","pos",-864607220),Ce=new U(null,"fallback-impl","fallback-impl",-1501286995),sa=new U(null,"flush-on-newline","flush-on-newline",-151457939),Ge=new U(null,"size","size",1098693007),ta=new U(null,"readably","readably",1129599760),ve=new U(null,"more-marker","more-marker",-14717935),wa=new U(null,"print-length","print-length",1931866356),Be=new U(null,
"alt-impl","alt-impl",670969595),He=new U(null,"shade","shade",-1569952450);var Ie=document.getElementById("canvas"),Je=Ie.getContext("2d"),Ke=Ie.width/2,Le=Ie.height/2;function Me(a){var b=sc(a)?Tc(ad,a):a,c=ec(b,Fe);a=T(c,0);var c=T(c,1),d=ec(b,Ge),b=ec(b,He),b=parseInt(b),b=[C("rgb("),C(b),C(","),C(b),C(","),C(b),C(")")].join("");Je.fillStyle=b;Je.fillRect(a,c,d,d)}function Ne(a){var b=T(a,0),c=T(a,1),d=T(a,2);a=180/d;d=1-d/32;return new qa(null,3,[Fe,new X(null,2,5,ud,[b*a+Ke,c*a+Le],null),Ge,3*d,He,255*d],null)}
function Oe(a){return new X(null,3,5,ud,[Ee(50)-25,Ee(50)-25,a],null)}function Pe(){return function b(c){return new Ic(null,function(){for(;;){var d=L(c);if(d){if(oc(d)){var e=qb(d),g=S(e),h=new Kc(Array(g),0);a:for(var k=0;;)if(k<g)D.c(e,k),h.add(Oe(Ee(32))),k+=1;else{e=!0;break a}return e?Nc(h.ca(),b(rb(d))):Nc(h.ca(),null)}N(d);return R(Oe(Ee(32)),b(Jb(d)))}return null}},null,null)}(new te(null,0,500,1,null))}
function Qe(a){return function c(a){return new Ic(null,function(){for(;;){var e=L(a);if(e){if(oc(e)){var g=qb(e),h=S(g),k=new Kc(Array(h),0);a:for(var l=0;;)if(l<h){var m=D.c(g,l),n=T(m,0),p=T(m,1),m=T(m,2)-.15;k.add(0>m?Oe(32):new X(null,3,5,ud,[n,p,m],null));l+=1}else{g=!0;break a}return g?Nc(k.ca(),c(rb(e))):Nc(k.ca(),null)}h=N(e);k=T(h,0);g=T(h,1);h=T(h,2)-.15;return R(0>h?Oe(32):new X(null,3,5,ud,[k,g,h],null),c(Jb(e)))}return null}},null,null)}(a)}
function Re(){var a=function(){var a=Pe();return $c?$c(a):Yc.call(null,a)}();return window.setInterval(function(a){return function(){a:{var c=ed.c(a,Qe);Je.fillStyle="black";Je.fillRect(0,0,Ie.width,Ie.height);for(var c=L(V.c(Ne,c)),d=null,e=0,g=0;;)if(g<e){var h=d.J(null,g);Me(h);g+=1}else if(c=L(c))d=c,oc(d)?(c=qb(d),e=rb(d),d=c,h=S(c),c=e,e=h):(h=N(d),Me(h),c=O(d),d=null,e=0),g=0;else break a}return null}}(a),15)}var Se=["starfield","core","init"],Te=this;
Se[0]in Te||!Te.execScript||Te.execScript("var "+Se[0]);for(var Ue;Se.length&&(Ue=Se.shift());){var Ve;if(Ve=!Se.length)Ve=void 0!==Re;Ve?Te[Ue]=Re:Te=Te[Ue]?Te[Ue]:Te[Ue]={}};